-- +goose Up

-- Track whether a VTIMEZONE came from a CalDAV server ('remote') or was
-- generated locally ('local'). Remote VTIMEZONEs are re-emitted verbatim
-- on export to avoid false dirty flags during sync.
ALTER TABLE timezones ADD COLUMN source TEXT NOT NULL DEFAULT 'local';
-- 'local'  = generated by chroncal via buildVTimezone
-- 'remote' = received verbatim from a CalDAV server

-- +goose Down
ALTER TABLE timezones DROP COLUMN source;
