linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - makezero
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-dirs:
    - internal/storage # sqlc-generated code
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
