version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - makezero
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - internal/storage
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
