// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package storage

import (
	"context"
)

const advanceCurrentCredentialAccountWatermark = `-- name: AdvanceCurrentCredentialAccountWatermark :exec
UPDATE credential_locations
SET max_account_id = MAX(max_account_id, ?)
WHERE location = (
    SELECT current_location
    FROM credential_namespace
    WHERE id = 1
)
`

func (q *Queries) AdvanceCurrentCredentialAccountWatermark(ctx context.Context, max interface{}) error {
	_, err := q.db.ExecContext(ctx, advanceCurrentCredentialAccountWatermark, max)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, server_url, auth_type, username)
VALUES (?, ?, ?, ?)
RETURNING id, name, server_url, auth_type, username, created_at, updated_at
`

type CreateAccountParams struct {
	Name      string
	ServerUrl string
	AuthType  string
	Username  string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.ServerUrl,
		arg.AuthType,
		arg.Username,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerUrl,
		&i.AuthType,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, server_url, auth_type, username, created_at, updated_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerUrl,
		&i.AuthType,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, server_url, auth_type, username, created_at, updated_at FROM accounts WHERE name = ? LIMIT 1
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerUrl,
		&i.AuthType,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, server_url, auth_type, username, created_at, updated_at FROM accounts ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServerUrl,
			&i.AuthType,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET
    name = ?,
    server_url = ?,
    auth_type = ?,
    username = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateAccountParams struct {
	Name      string
	ServerUrl string
	AuthType  string
	Username  string
	ID        int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.ServerUrl,
		arg.AuthType,
		arg.Username,
		arg.ID,
	)
	return err
}
