// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarm_state.sql

package storage

import (
	"context"
)

const acknowledgeAlarmState = `-- name: AcknowledgeAlarmState :exec
UPDATE alarm_state SET acked_at = ? WHERE id = ?
`

type AcknowledgeAlarmStateParams struct {
	AckedAt *string
	ID      int64
}

func (q *Queries) AcknowledgeAlarmState(ctx context.Context, arg AcknowledgeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAlarmState, arg.AckedAt, arg.ID)
	return err
}

const createAlarmState = `-- name: CreateAlarmState :one
INSERT INTO alarm_state (alarm_id, event_id, trigger_at, fired_at)
SELECT ?1, ?2, ?3, ?4
WHERE EXISTS (
    SELECT 1 FROM event_alarms
    WHERE id = ?1 AND action IN ('AUDIO','DISPLAY','EMAIL')
)
RETURNING id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to
`

type CreateAlarmStateParams struct {
	AlarmID   int64
	EventID   int64
	TriggerAt string
	FiredAt   *string
}

// Claim a fire slot for one alarm. The EXISTS arm reads the action in the
// same statement as the insert, so a sync pull that rewrites the alarm to
// a sync-only action between the check and the claim cannot leave a fired
// state for an alarm the user disabled (issue #579). Zero rows means the
// claim failed, and the caller reports sql.ErrNoRows.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) CreateAlarmState(ctx context.Context, arg CreateAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, createAlarmState,
		arg.AlarmID,
		arg.EventID,
		arg.TriggerAt,
		arg.FiredAt,
	)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const deleteAlarmStatesByEventID = `-- name: DeleteAlarmStatesByEventID :exec
DELETE FROM alarm_state WHERE event_id = ?
`

func (q *Queries) DeleteAlarmStatesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmStatesByEventID, eventID)
	return err
}

const getAlarmState = `-- name: GetAlarmState :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE alarm_id = ? AND trigger_at = ?
`

type GetAlarmStateParams struct {
	AlarmID   int64
	TriggerAt string
}

func (q *Queries) GetAlarmState(ctx context.Context, arg GetAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmState, arg.AlarmID, arg.TriggerAt)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const getAlarmStateByID = `-- name: GetAlarmStateByID :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE id = ?
`

func (q *Queries) GetAlarmStateByID(ctx context.Context, id int64) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmStateByID, id)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const listAlarmStatesByEventID = `-- name: ListAlarmStatesByEventID :many
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE event_id = ? ORDER BY trigger_at
`

func (q *Queries) ListAlarmStatesByEventID(ctx context.Context, eventID int64) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmStatesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSnoozedAlarmStates = `-- name: ListExpiredSnoozedAlarmStates :many
SELECT s.id, s.alarm_id, s.event_id, s.trigger_at, s.fired_at, s.acked_at, s.snoozed_to FROM alarm_state s
JOIN event_alarms a ON a.id = s.alarm_id
WHERE s.fired_at IS NOT NULL
  AND s.acked_at IS NULL
  AND s.snoozed_to IS NOT NULL
  AND s.snoozed_to <= ?
  AND a.action IN ('AUDIO','DISPLAY','EMAIL')
ORDER BY s.snoozed_to
`

// The same sync-only filter as ListPendingAlarmStates, for the re-fire path.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) ListExpiredSnoozedAlarmStates(ctx context.Context, snoozedTo *string) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredSnoozedAlarmStates, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAlarmStates = `-- name: ListPendingAlarmStates :many
SELECT s.id, s.alarm_id, s.event_id, s.trigger_at, s.fired_at, s.acked_at, s.snoozed_to FROM alarm_state s
JOIN event_alarms a ON a.id = s.alarm_id
WHERE s.acked_at IS NULL AND s.fired_at IS NOT NULL
  AND a.action IN ('AUDIO','DISPLAY','EMAIL')
ORDER BY s.trigger_at
`

// Hide the state of an alarm a sync pull rewrote to a sync-only action.
// The filter reads the current action, so the row comes back when a later
// pull restores a fireable action (issue #579). A retirement that wrote
// acked_at instead would consume the snooze of the user for good.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) ListPendingAlarmStates(ctx context.Context) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAlarmStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAcknowledgedAlarmStates = `-- name: PurgeAcknowledgedAlarmStates :execrows
DELETE FROM alarm_state WHERE acked_at IS NOT NULL AND trigger_at < ?
`

func (q *Queries) PurgeAcknowledgedAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAcknowledgedAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeStaleUnacknowledgedAlarmStates = `-- name: PurgeStaleUnacknowledgedAlarmStates :execrows
DELETE FROM alarm_state
WHERE acked_at IS NULL
  AND trigger_at < ?
  AND (snoozed_to IS NULL OR snoozed_to < trigger_at)
`

func (q *Queries) PurgeStaleUnacknowledgedAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeStaleUnacknowledgedAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refireAlarmState = `-- name: RefireAlarmState :execrows
UPDATE alarm_state SET fired_at = ?, snoozed_to = NULL
WHERE id = ? AND snoozed_to IS NOT NULL
`

type RefireAlarmStateParams struct {
	FiredAt *string
	ID      int64
}

func (q *Queries) RefireAlarmState(ctx context.Context, arg RefireAlarmStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refireAlarmState, arg.FiredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const snoozeAlarmState = `-- name: SnoozeAlarmState :exec
UPDATE alarm_state SET snoozed_to = ? WHERE id = ?
`

type SnoozeAlarmStateParams struct {
	SnoozedTo *string
	ID        int64
}

func (q *Queries) SnoozeAlarmState(ctx context.Context, arg SnoozeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, snoozeAlarmState, arg.SnoozedTo, arg.ID)
	return err
}
