// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarm_state.sql

package storage

import (
	"context"
)

const acknowledgeAlarmState = `-- name: AcknowledgeAlarmState :exec
UPDATE alarm_state SET acked_at = ? WHERE id = ?
`

type AcknowledgeAlarmStateParams struct {
	AckedAt *string
	ID      int64
}

func (q *Queries) AcknowledgeAlarmState(ctx context.Context, arg AcknowledgeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAlarmState, arg.AckedAt, arg.ID)
	return err
}

const createAlarmState = `-- name: CreateAlarmState :one
INSERT INTO alarm_state (alarm_id, event_id, trigger_at, fired_at)
VALUES (?, ?, ?, ?) RETURNING id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to
`

type CreateAlarmStateParams struct {
	AlarmID   int64
	EventID   int64
	TriggerAt string
	FiredAt   *string
}

func (q *Queries) CreateAlarmState(ctx context.Context, arg CreateAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, createAlarmState,
		arg.AlarmID,
		arg.EventID,
		arg.TriggerAt,
		arg.FiredAt,
	)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const deleteAlarmStatesByEventID = `-- name: DeleteAlarmStatesByEventID :exec
DELETE FROM alarm_state WHERE event_id = ?
`

func (q *Queries) DeleteAlarmStatesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmStatesByEventID, eventID)
	return err
}

const getAlarmState = `-- name: GetAlarmState :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE alarm_id = ? AND trigger_at = ?
`

type GetAlarmStateParams struct {
	AlarmID   int64
	TriggerAt string
}

func (q *Queries) GetAlarmState(ctx context.Context, arg GetAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmState, arg.AlarmID, arg.TriggerAt)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const getAlarmStateByID = `-- name: GetAlarmStateByID :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE id = ?
`

func (q *Queries) GetAlarmStateByID(ctx context.Context, id int64) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmStateByID, id)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const listAlarmStatesByEventID = `-- name: ListAlarmStatesByEventID :many
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE event_id = ? ORDER BY trigger_at
`

func (q *Queries) ListAlarmStatesByEventID(ctx context.Context, eventID int64) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmStatesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSnoozedAlarmStates = `-- name: ListExpiredSnoozedAlarmStates :many
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state
WHERE fired_at IS NOT NULL
  AND acked_at IS NULL
  AND snoozed_to IS NOT NULL
  AND snoozed_to <= ?
ORDER BY snoozed_to
`

func (q *Queries) ListExpiredSnoozedAlarmStates(ctx context.Context, snoozedTo *string) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredSnoozedAlarmStates, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAlarmStates = `-- name: ListPendingAlarmStates :many
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to FROM alarm_state WHERE acked_at IS NULL AND fired_at IS NOT NULL ORDER BY trigger_at
`

func (q *Queries) ListPendingAlarmStates(ctx context.Context) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAlarmStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refireAlarmState = `-- name: RefireAlarmState :exec
UPDATE alarm_state SET fired_at = ?, snoozed_to = NULL WHERE id = ?
`

type RefireAlarmStateParams struct {
	FiredAt *string
	ID      int64
}

func (q *Queries) RefireAlarmState(ctx context.Context, arg RefireAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, refireAlarmState, arg.FiredAt, arg.ID)
	return err
}

const snoozeAlarmState = `-- name: SnoozeAlarmState :exec
UPDATE alarm_state SET snoozed_to = ? WHERE id = ?
`

type SnoozeAlarmStateParams struct {
	SnoozedTo *string
	ID        int64
}

func (q *Queries) SnoozeAlarmState(ctx context.Context, arg SnoozeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, snoozeAlarmState, arg.SnoozedTo, arg.ID)
	return err
}
