// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarms.sql

package storage

import (
	"context"
	"strings"
)

const createAlarm = `-- name: CreateAlarm :one
INSERT INTO event_alarms (event_id, uid, action, trigger_value, description, summary, repeat, duration, related, acknowledged, attach_uri, attach_fmttype)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype
`

type CreateAlarmParams struct {
	EventID       int64
	Uid           *string
	Action        string
	TriggerValue  string
	Description   *string
	Summary       *string
	Repeat        int64
	Duration      *string
	Related       string
	Acknowledged  *string
	AttachUri     *string
	AttachFmttype *string
}

func (q *Queries) CreateAlarm(ctx context.Context, arg CreateAlarmParams) (EventAlarm, error) {
	row := q.db.QueryRowContext(ctx, createAlarm,
		arg.EventID,
		arg.Uid,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Summary,
		arg.Repeat,
		arg.Duration,
		arg.Related,
		arg.Acknowledged,
		arg.AttachUri,
		arg.AttachFmttype,
	)
	var i EventAlarm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.Description,
		&i.Repeat,
		&i.Duration,
		&i.Related,
		&i.Summary,
		&i.Uid,
		&i.Acknowledged,
		&i.AttachUri,
		&i.AttachFmttype,
	)
	return i, err
}

const deleteAlarmByID = `-- name: DeleteAlarmByID :exec
DELETE FROM event_alarms WHERE id = ?
`

func (q *Queries) DeleteAlarmByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmByID, id)
	return err
}

const deleteAlarmsByEventID = `-- name: DeleteAlarmsByEventID :exec
DELETE FROM event_alarms WHERE event_id = ?
`

func (q *Queries) DeleteAlarmsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmsByEventID, eventID)
	return err
}

const listAlarmsByEventID = `-- name: ListAlarmsByEventID :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype FROM event_alarms WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListAlarmsByEventID(ctx context.Context, eventID int64) ([]EventAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
			&i.Acknowledged,
			&i.AttachUri,
			&i.AttachFmttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlarmsByEventIDs = `-- name: ListAlarmsByEventIDs :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype FROM event_alarms WHERE event_id IN (/*SLICE:event_ids*/?) ORDER BY event_id, id
`

func (q *Queries) ListAlarmsByEventIDs(ctx context.Context, eventIds []int64) ([]EventAlarm, error) {
	query := listAlarmsByEventIDs
	var queryParams []interface{}
	if len(eventIds) > 0 {
		for _, v := range eventIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:event_ids*/?", strings.Repeat(",?", len(eventIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:event_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
			&i.Acknowledged,
			&i.AttachUri,
			&i.AttachFmttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlarmsWithEmptyUID = `-- name: ListAlarmsWithEmptyUID :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype FROM event_alarms WHERE uid IS NULL
`

func (q *Queries) ListAlarmsWithEmptyUID(ctx context.Context) ([]EventAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmsWithEmptyUID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
			&i.Acknowledged,
			&i.AttachUri,
			&i.AttachFmttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctAlarmTriggers = `-- name: ListDistinctAlarmTriggers :many
SELECT DISTINCT trigger_value FROM event_alarms
`

func (q *Queries) ListDistinctAlarmTriggers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctAlarmTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var trigger_value string
		if err := rows.Scan(&trigger_value); err != nil {
			return nil, err
		}
		items = append(items, trigger_value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlarmAcknowledged = `-- name: UpdateAlarmAcknowledged :exec
UPDATE event_alarms SET acknowledged = ? WHERE id = ? AND event_id = ?
`

type UpdateAlarmAcknowledgedParams struct {
	Acknowledged *string
	ID           int64
	EventID      int64
}

func (q *Queries) UpdateAlarmAcknowledged(ctx context.Context, arg UpdateAlarmAcknowledgedParams) error {
	_, err := q.db.ExecContext(ctx, updateAlarmAcknowledged, arg.Acknowledged, arg.ID, arg.EventID)
	return err
}

const updateAlarmContentByID = `-- name: UpdateAlarmContentByID :exec
UPDATE event_alarms
SET action = ?, trigger_value = ?, description = ?, summary = ?, repeat = ?,
    duration = ?, related = ?, acknowledged = ?, attach_uri = ?, attach_fmttype = ?
WHERE id = ? AND event_id = ?
`

type UpdateAlarmContentByIDParams struct {
	Action        string
	TriggerValue  string
	Description   *string
	Summary       *string
	Repeat        int64
	Duration      *string
	Related       string
	Acknowledged  *string
	AttachUri     *string
	AttachFmttype *string
	ID            int64
	EventID       int64
}

func (q *Queries) UpdateAlarmContentByID(ctx context.Context, arg UpdateAlarmContentByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAlarmContentByID,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Summary,
		arg.Repeat,
		arg.Duration,
		arg.Related,
		arg.Acknowledged,
		arg.AttachUri,
		arg.AttachFmttype,
		arg.ID,
		arg.EventID,
	)
	return err
}

const updateAlarmUID = `-- name: UpdateAlarmUID :exec
UPDATE event_alarms SET uid = ? WHERE id = ?
`

type UpdateAlarmUIDParams struct {
	Uid *string
	ID  int64
}

func (q *Queries) UpdateAlarmUID(ctx context.Context, arg UpdateAlarmUIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAlarmUID, arg.Uid, arg.ID)
	return err
}
