// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarm_attendees.sql

package storage

import (
	"context"
)

const createAlarmAttendee = `-- name: CreateAlarmAttendee :one
INSERT INTO event_alarm_attendees (alarm_id, email, name) VALUES (?, ?, ?) RETURNING id, alarm_id, email, name
`

type CreateAlarmAttendeeParams struct {
	AlarmID int64
	Email   string
	Name    *string
}

func (q *Queries) CreateAlarmAttendee(ctx context.Context, arg CreateAlarmAttendeeParams) (EventAlarmAttendee, error) {
	row := q.db.QueryRowContext(ctx, createAlarmAttendee, arg.AlarmID, arg.Email, arg.Name)
	var i EventAlarmAttendee
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const deleteAlarmAttendeesByAlarmID = `-- name: DeleteAlarmAttendeesByAlarmID :exec
DELETE FROM event_alarm_attendees WHERE alarm_id = ?
`

func (q *Queries) DeleteAlarmAttendeesByAlarmID(ctx context.Context, alarmID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmAttendeesByAlarmID, alarmID)
	return err
}

const listAlarmAttendeesByAlarmID = `-- name: ListAlarmAttendeesByAlarmID :many
SELECT id, alarm_id, email, name FROM event_alarm_attendees WHERE alarm_id = ? ORDER BY id
`

func (q *Queries) ListAlarmAttendeesByAlarmID(ctx context.Context, alarmID int64) ([]EventAlarmAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmAttendeesByAlarmID, alarmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarmAttendee
	for rows.Next() {
		var i EventAlarmAttendee
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
