// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarms.sql

package storage

import (
	"context"
)

const createAlarm = `-- name: CreateAlarm :one
INSERT INTO event_alarms (event_id, action, trigger_value, description, repeat, duration, related)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, event_id, "action", trigger_value, description, repeat, duration, related
`

type CreateAlarmParams struct {
	EventID      int64
	Action       string
	TriggerValue string
	Description  string
	Repeat       int64
	Duration     string
	Related      string
}

func (q *Queries) CreateAlarm(ctx context.Context, arg CreateAlarmParams) (EventAlarm, error) {
	row := q.db.QueryRowContext(ctx, createAlarm,
		arg.EventID,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Repeat,
		arg.Duration,
		arg.Related,
	)
	var i EventAlarm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.Description,
		&i.Repeat,
		&i.Duration,
		&i.Related,
	)
	return i, err
}

const deleteAlarmsByEventID = `-- name: DeleteAlarmsByEventID :exec
DELETE FROM event_alarms WHERE event_id = ?
`

func (q *Queries) DeleteAlarmsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmsByEventID, eventID)
	return err
}

const listAlarmsByEventID = `-- name: ListAlarmsByEventID :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related FROM event_alarms WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListAlarmsByEventID(ctx context.Context, eventID int64) ([]EventAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
