// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarms.sql

package storage

import (
	"context"
)

const createAlarm = `-- name: CreateAlarm :one
INSERT INTO event_alarms (event_id, uid, action, trigger_value, description, summary, repeat, duration, related)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid
`

type CreateAlarmParams struct {
	EventID      int64
	Uid          string
	Action       string
	TriggerValue string
	Description  string
	Summary      string
	Repeat       int64
	Duration     string
	Related      string
}

func (q *Queries) CreateAlarm(ctx context.Context, arg CreateAlarmParams) (EventAlarm, error) {
	row := q.db.QueryRowContext(ctx, createAlarm,
		arg.EventID,
		arg.Uid,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Summary,
		arg.Repeat,
		arg.Duration,
		arg.Related,
	)
	var i EventAlarm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.Description,
		&i.Repeat,
		&i.Duration,
		&i.Related,
		&i.Summary,
		&i.Uid,
	)
	return i, err
}

const deleteAlarmByID = `-- name: DeleteAlarmByID :exec
DELETE FROM event_alarms WHERE id = ?
`

func (q *Queries) DeleteAlarmByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmByID, id)
	return err
}

const deleteAlarmsByEventID = `-- name: DeleteAlarmsByEventID :exec
DELETE FROM event_alarms WHERE event_id = ?
`

func (q *Queries) DeleteAlarmsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmsByEventID, eventID)
	return err
}

const listAlarmsByEventID = `-- name: ListAlarmsByEventID :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid FROM event_alarms WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListAlarmsByEventID(ctx context.Context, eventID int64) ([]EventAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlarmsWithEmptyUID = `-- name: ListAlarmsWithEmptyUID :many
SELECT id, event_id, "action", trigger_value, description, repeat, duration, related, summary, uid FROM event_alarms WHERE uid = ''
`

func (q *Queries) ListAlarmsWithEmptyUID(ctx context.Context) ([]EventAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmsWithEmptyUID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAlarm
	for rows.Next() {
		var i EventAlarm
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlarmUID = `-- name: UpdateAlarmUID :exec
UPDATE event_alarms SET uid = ? WHERE id = ?
`

type UpdateAlarmUIDParams struct {
	Uid string
	ID  int64
}

func (q *Queries) UpdateAlarmUID(ctx context.Context, arg UpdateAlarmUIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAlarmUID, arg.Uid, arg.ID)
	return err
}
