// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendees.sql

package storage

import (
	"context"
)

const createAttendee = `-- name: CreateAttendee :one
INSERT INTO event_attendees (event_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, event_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language
`

type CreateAttendeeParams struct {
	EventID       int64
	Email         string
	Name          string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        string
	Rsvp          string
	SentBy        string
	DelegatedTo   string
	DelegatedFrom string
	Member        string
	Dir           string
	Language      string
}

func (q *Queries) CreateAttendee(ctx context.Context, arg CreateAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRowContext(ctx, createAttendee,
		arg.EventID,
		arg.Email,
		arg.Name,
		arg.RsvpStatus,
		arg.Role,
		arg.Organizer,
		arg.Cutype,
		arg.Rsvp,
		arg.SentBy,
		arg.DelegatedTo,
		arg.DelegatedFrom,
		arg.Member,
		arg.Dir,
		arg.Language,
	)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Email,
		&i.Name,
		&i.RsvpStatus,
		&i.Role,
		&i.Organizer,
		&i.Cutype,
		&i.Rsvp,
		&i.SentBy,
		&i.DelegatedTo,
		&i.DelegatedFrom,
		&i.Member,
		&i.Dir,
		&i.Language,
	)
	return i, err
}

const deleteAttendeesByEventID = `-- name: DeleteAttendeesByEventID :exec
DELETE FROM event_attendees WHERE event_id = ?
`

func (q *Queries) DeleteAttendeesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttendeesByEventID, eventID)
	return err
}

const listAttendeesByEventID = `-- name: ListAttendeesByEventID :many
SELECT id, event_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language FROM event_attendees WHERE event_id = ? ORDER BY organizer DESC, name
`

func (q *Queries) ListAttendeesByEventID(ctx context.Context, eventID int64) ([]EventAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listAttendeesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAttendee
	for rows.Next() {
		var i EventAttendee
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Email,
			&i.Name,
			&i.RsvpStatus,
			&i.Role,
			&i.Organizer,
			&i.Cutype,
			&i.Rsvp,
			&i.SentBy,
			&i.DelegatedTo,
			&i.DelegatedFrom,
			&i.Member,
			&i.Dir,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
