// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendees.sql

package storage

import (
	"context"
)

const createAttendee = `-- name: CreateAttendee :one
INSERT INTO event_attendees (event_id, email, name, rsvp_status, role, organizer)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, event_id, email, name, rsvp_status, role, organizer
`

type CreateAttendeeParams struct {
	EventID    int64
	Email      string
	Name       string
	RsvpStatus string
	Role       string
	Organizer  int64
}

func (q *Queries) CreateAttendee(ctx context.Context, arg CreateAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRowContext(ctx, createAttendee,
		arg.EventID,
		arg.Email,
		arg.Name,
		arg.RsvpStatus,
		arg.Role,
		arg.Organizer,
	)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Email,
		&i.Name,
		&i.RsvpStatus,
		&i.Role,
		&i.Organizer,
	)
	return i, err
}

const deleteAttendeesByEventID = `-- name: DeleteAttendeesByEventID :exec
DELETE FROM event_attendees WHERE event_id = ?
`

func (q *Queries) DeleteAttendeesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttendeesByEventID, eventID)
	return err
}

const listAttendeesByEventID = `-- name: ListAttendeesByEventID :many
SELECT id, event_id, email, name, rsvp_status, role, organizer FROM event_attendees WHERE event_id = ? ORDER BY organizer DESC, name
`

func (q *Queries) ListAttendeesByEventID(ctx context.Context, eventID int64) ([]EventAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listAttendeesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAttendee
	for rows.Next() {
		var i EventAttendee
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Email,
			&i.Name,
			&i.RsvpStatus,
			&i.Role,
			&i.Organizer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
