// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package storage

import (
	"context"
)

const clearCalendarColorDirty = `-- name: ClearCalendarColorDirty :exec
UPDATE calendars SET
    remote_color = ?,
    color_dirty = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type ClearCalendarColorDirtyParams struct {
	RemoteColor *string
	ID          int64
}

func (q *Queries) ClearCalendarColorDirty(ctx context.Context, arg ClearCalendarColorDirtyParams) error {
	_, err := q.db.ExecContext(ctx, clearCalendarColorDirty, arg.RemoteColor, arg.ID)
	return err
}

const clearDefaultCalendar = `-- name: ClearDefaultCalendar :exec
UPDATE calendars SET
    is_default = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE is_default = 1
`

func (q *Queries) ClearDefaultCalendar(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultCalendar)
	return err
}

const countCalendars = `-- name: CountCalendars :one
SELECT COUNT(*) FROM calendars
`

func (q *Queries) CountCalendars(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalendars)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDefaultCalendars = `-- name: CountDefaultCalendars :one
SELECT COUNT(*) FROM calendars WHERE is_default = 1
`

func (q *Queries) CountDefaultCalendars(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDefaultCalendars)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (name, color, description, display_order)
VALUES (?, ?, ?, (SELECT COALESCE(MAX(display_order), -1) + 1 FROM calendars))
RETURNING id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing
`

type CreateCalendarParams struct {
	Name        string
	Color       string
	Description *string
}

// display_order is computed as MAX+1 (0 for the first calendar) so new
// calendars append to the bottom of the sidebar instead of all colliding at 0.
func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, createCalendar, arg.Name, arg.Color, arg.Description)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.RemoteUrl,
		&i.Ctag,
		&i.SyncToken,
		&i.LastSyncAt,
		&i.LastSyncAttemptedAt,
		&i.LastSyncError,
		&i.RemoteColor,
		&i.ColorDirty,
		&i.OwnerEmail,
		&i.IsDefault,
		&i.DisplayOrder,
		&i.RemoteName,
		&i.RemoteAccess,
		&i.RemoteComponents,
		&i.RemoteMissing,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars WHERE id = ?
`

func (q *Queries) DeleteCalendar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, id)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing FROM calendars WHERE id = ?
`

func (q *Queries) GetCalendar(ctx context.Context, id int64) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getCalendar, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.RemoteUrl,
		&i.Ctag,
		&i.SyncToken,
		&i.LastSyncAt,
		&i.LastSyncAttemptedAt,
		&i.LastSyncError,
		&i.RemoteColor,
		&i.ColorDirty,
		&i.OwnerEmail,
		&i.IsDefault,
		&i.DisplayOrder,
		&i.RemoteName,
		&i.RemoteAccess,
		&i.RemoteComponents,
		&i.RemoteMissing,
	)
	return i, err
}

const getDefaultCalendar = `-- name: GetDefaultCalendar :one
SELECT id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing FROM calendars WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultCalendar(ctx context.Context) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCalendar)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.RemoteUrl,
		&i.Ctag,
		&i.SyncToken,
		&i.LastSyncAt,
		&i.LastSyncAttemptedAt,
		&i.LastSyncError,
		&i.RemoteColor,
		&i.ColorDirty,
		&i.OwnerEmail,
		&i.IsDefault,
		&i.DisplayOrder,
		&i.RemoteName,
		&i.RemoteAccess,
		&i.RemoteComponents,
		&i.RemoteMissing,
	)
	return i, err
}

const linkCalendarToAccount = `-- name: LinkCalendarToAccount :exec
UPDATE calendars SET
    account_id = ?,
    remote_url = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type LinkCalendarToAccountParams struct {
	AccountID *int64
	RemoteUrl *string
	ID        int64
}

func (q *Queries) LinkCalendarToAccount(ctx context.Context, arg LinkCalendarToAccountParams) error {
	_, err := q.db.ExecContext(ctx, linkCalendarToAccount, arg.AccountID, arg.RemoteUrl, arg.ID)
	return err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing FROM calendars ORDER BY display_order, name
`

func (q *Queries) ListCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.RemoteUrl,
			&i.Ctag,
			&i.SyncToken,
			&i.LastSyncAt,
			&i.LastSyncAttemptedAt,
			&i.LastSyncError,
			&i.RemoteColor,
			&i.ColorDirty,
			&i.OwnerEmail,
			&i.IsDefault,
			&i.DisplayOrder,
			&i.RemoteName,
			&i.RemoteAccess,
			&i.RemoteComponents,
			&i.RemoteMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarsByAccount = `-- name: ListCalendarsByAccount :many
SELECT id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing FROM calendars WHERE account_id = ? ORDER BY display_order, name
`

func (q *Queries) ListCalendarsByAccount(ctx context.Context, accountID *int64) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.RemoteUrl,
			&i.Ctag,
			&i.SyncToken,
			&i.LastSyncAt,
			&i.LastSyncAttemptedAt,
			&i.LastSyncError,
			&i.RemoteColor,
			&i.ColorDirty,
			&i.OwnerEmail,
			&i.IsDefault,
			&i.DisplayOrder,
			&i.RemoteName,
			&i.RemoteAccess,
			&i.RemoteComponents,
			&i.RemoteMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCalendarColorDirty = `-- name: MarkCalendarColorDirty :exec
UPDATE calendars SET
    color_dirty = 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) MarkCalendarColorDirty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCalendarColorDirty, id)
	return err
}

const setCalendarAsDefault = `-- name: SetCalendarAsDefault :exec
UPDATE calendars SET
    is_default = 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) SetCalendarAsDefault(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setCalendarAsDefault, id)
	return err
}

const setCalendarDisplayOrder = `-- name: SetCalendarDisplayOrder :exec
UPDATE calendars SET
    display_order = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type SetCalendarDisplayOrderParams struct {
	DisplayOrder int64
	ID           int64
}

func (q *Queries) SetCalendarDisplayOrder(ctx context.Context, arg SetCalendarDisplayOrderParams) error {
	_, err := q.db.ExecContext(ctx, setCalendarDisplayOrder, arg.DisplayOrder, arg.ID)
	return err
}

const updateCalendar = `-- name: UpdateCalendar :one
UPDATE calendars SET name = ?, color = ?, description = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ? RETURNING id, name, color, description, created_at, updated_at, account_id, remote_url, ctag, sync_token, last_sync_at, last_sync_attempted_at, last_sync_error, remote_color, color_dirty, owner_email, is_default, display_order, remote_name, remote_access, remote_components, remote_missing
`

type UpdateCalendarParams struct {
	Name        string
	Color       string
	Description *string
	ID          int64
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, updateCalendar,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.ID,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.RemoteUrl,
		&i.Ctag,
		&i.SyncToken,
		&i.LastSyncAt,
		&i.LastSyncAttemptedAt,
		&i.LastSyncError,
		&i.RemoteColor,
		&i.ColorDirty,
		&i.OwnerEmail,
		&i.IsDefault,
		&i.DisplayOrder,
		&i.RemoteName,
		&i.RemoteAccess,
		&i.RemoteComponents,
		&i.RemoteMissing,
	)
	return i, err
}

const updateCalendarColorFromSync = `-- name: UpdateCalendarColorFromSync :exec
UPDATE calendars SET
    color = ?,
    remote_color = ?,
    color_dirty = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateCalendarColorFromSyncParams struct {
	Color       string
	RemoteColor *string
	ID          int64
}

func (q *Queries) UpdateCalendarColorFromSync(ctx context.Context, arg UpdateCalendarColorFromSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarColorFromSync, arg.Color, arg.RemoteColor, arg.ID)
	return err
}

const updateCalendarOwnerEmail = `-- name: UpdateCalendarOwnerEmail :exec
UPDATE calendars SET
    owner_email = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateCalendarOwnerEmailParams struct {
	OwnerEmail string
	ID         int64
}

func (q *Queries) UpdateCalendarOwnerEmail(ctx context.Context, arg UpdateCalendarOwnerEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarOwnerEmail, arg.OwnerEmail, arg.ID)
	return err
}

const updateCalendarSyncHealth = `-- name: UpdateCalendarSyncHealth :exec
UPDATE calendars SET
    last_sync_attempted_at = ?,
    last_sync_at = ?,
    last_sync_error = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateCalendarSyncHealthParams struct {
	LastSyncAttemptedAt *string
	LastSyncAt          *string
	LastSyncError       *string
	ID                  int64
}

func (q *Queries) UpdateCalendarSyncHealth(ctx context.Context, arg UpdateCalendarSyncHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarSyncHealth,
		arg.LastSyncAttemptedAt,
		arg.LastSyncAt,
		arg.LastSyncError,
		arg.ID,
	)
	return err
}

const updateCalendarSyncState = `-- name: UpdateCalendarSyncState :exec
UPDATE calendars SET
    ctag = ?,
    sync_token = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateCalendarSyncStateParams struct {
	Ctag      *string
	SyncToken *string
	ID        int64
}

func (q *Queries) UpdateCalendarSyncState(ctx context.Context, arg UpdateCalendarSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarSyncState, arg.Ctag, arg.SyncToken, arg.ID)
	return err
}
