// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package storage

import (
	"context"
)

const countCalendars = `-- name: CountCalendars :one
SELECT COUNT(*) FROM calendars
`

func (q *Queries) CountCalendars(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalendars)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (name, color, description) VALUES (?, ?, ?) RETURNING id, name, color, description, created_at, updated_at
`

type CreateCalendarParams struct {
	Name        string
	Color       string
	Description *string
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, createCalendar, arg.Name, arg.Color, arg.Description)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars WHERE id = ?
`

func (q *Queries) DeleteCalendar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, id)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT id, name, color, description, created_at, updated_at FROM calendars WHERE id = ?
`

func (q *Queries) GetCalendar(ctx context.Context, id int64) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getCalendar, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, name, color, description, created_at, updated_at FROM calendars ORDER BY name
`

func (q *Queries) ListCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :one
UPDATE calendars SET name = ?, color = ?, description = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ? RETURNING id, name, color, description, created_at, updated_at
`

type UpdateCalendarParams struct {
	Name        string
	Color       string
	Description *string
	ID          int64
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, updateCalendar,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.ID,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
