// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: default_alarm_state.sql

package storage

import (
	"context"
)

const acknowledgeDefaultAlarmState = `-- name: AcknowledgeDefaultAlarmState :exec
UPDATE default_alarm_state SET acked_at = ? WHERE id = ?
`

type AcknowledgeDefaultAlarmStateParams struct {
	AckedAt *string
	ID      int64
}

func (q *Queries) AcknowledgeDefaultAlarmState(ctx context.Context, arg AcknowledgeDefaultAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeDefaultAlarmState, arg.AckedAt, arg.ID)
	return err
}

const createDefaultAlarmState = `-- name: CreateDefaultAlarmState :one
INSERT INTO default_alarm_state (event_id, action, trigger_value, trigger_at, fired_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, event_id, "action", trigger_value, trigger_at, fired_at, acked_at, snoozed_to
`

type CreateDefaultAlarmStateParams struct {
	EventID      int64
	Action       string
	TriggerValue string
	TriggerAt    string
	FiredAt      *string
}

func (q *Queries) CreateDefaultAlarmState(ctx context.Context, arg CreateDefaultAlarmStateParams) (DefaultAlarmState, error) {
	row := q.db.QueryRowContext(ctx, createDefaultAlarmState,
		arg.EventID,
		arg.Action,
		arg.TriggerValue,
		arg.TriggerAt,
		arg.FiredAt,
	)
	var i DefaultAlarmState
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const getDefaultAlarmState = `-- name: GetDefaultAlarmState :one

SELECT id, event_id, "action", trigger_value, trigger_at, fired_at, acked_at, snoozed_to FROM default_alarm_state WHERE event_id = ? AND trigger_value = ? AND trigger_at = ?
`

type GetDefaultAlarmStateParams struct {
	EventID      int64
	TriggerValue string
	TriggerAt    string
}

// Operational state for default (virtual) alarms, issue #815. A default
// alarm has no event_alarms row, so it cannot share alarm_state (its
// alarm_id column references event_alarms). The
// (event_id, trigger_value, trigger_at) index makes CreateDefaultAlarmState
// an atomic claim, like idx_alarm_state_unique does for alarm_state.
func (q *Queries) GetDefaultAlarmState(ctx context.Context, arg GetDefaultAlarmStateParams) (DefaultAlarmState, error) {
	row := q.db.QueryRowContext(ctx, getDefaultAlarmState, arg.EventID, arg.TriggerValue, arg.TriggerAt)
	var i DefaultAlarmState
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const getDefaultAlarmStateByID = `-- name: GetDefaultAlarmStateByID :one
SELECT id, event_id, "action", trigger_value, trigger_at, fired_at, acked_at, snoozed_to FROM default_alarm_state WHERE id = ?
`

func (q *Queries) GetDefaultAlarmStateByID(ctx context.Context, id int64) (DefaultAlarmState, error) {
	row := q.db.QueryRowContext(ctx, getDefaultAlarmStateByID, id)
	var i DefaultAlarmState
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.TriggerValue,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const listExpiredSnoozedDefaultAlarmStates = `-- name: ListExpiredSnoozedDefaultAlarmStates :many
SELECT id, event_id, "action", trigger_value, trigger_at, fired_at, acked_at, snoozed_to FROM default_alarm_state
WHERE fired_at IS NOT NULL
  AND acked_at IS NULL
  AND snoozed_to IS NOT NULL
  AND snoozed_to <= ?
ORDER BY snoozed_to
`

// The same expired-snooze filter as ListExpiredSnoozedAlarmStates, for the
// re-fire path.
func (q *Queries) ListExpiredSnoozedDefaultAlarmStates(ctx context.Context, snoozedTo *string) ([]DefaultAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredSnoozedDefaultAlarmStates, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DefaultAlarmState
	for rows.Next() {
		var i DefaultAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDefaultAlarmStates = `-- name: ListPendingDefaultAlarmStates :many
SELECT id, event_id, "action", trigger_value, trigger_at, fired_at, acked_at, snoozed_to FROM default_alarm_state
WHERE acked_at IS NULL AND fired_at IS NOT NULL
ORDER BY trigger_at
`

func (q *Queries) ListPendingDefaultAlarmStates(ctx context.Context) ([]DefaultAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDefaultAlarmStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DefaultAlarmState
	for rows.Next() {
		var i DefaultAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.TriggerValue,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAcknowledgedDefaultAlarmStates = `-- name: PurgeAcknowledgedDefaultAlarmStates :execrows
DELETE FROM default_alarm_state WHERE acked_at IS NOT NULL AND trigger_at < ?
`

func (q *Queries) PurgeAcknowledgedDefaultAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAcknowledgedDefaultAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeStaleUnacknowledgedDefaultAlarmStates = `-- name: PurgeStaleUnacknowledgedDefaultAlarmStates :execrows
DELETE FROM default_alarm_state
WHERE acked_at IS NULL
  AND trigger_at < ?
  AND (snoozed_to IS NULL OR snoozed_to < trigger_at)
`

// The same stale-row filter as PurgeStaleUnacknowledgedAlarmStates: a
// rescheduled event leaves unfired trigger rows behind. Delete the ones
// that no checker will ever fire again.
func (q *Queries) PurgeStaleUnacknowledgedDefaultAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeStaleUnacknowledgedDefaultAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refireDefaultAlarmState = `-- name: RefireDefaultAlarmState :execrows
UPDATE default_alarm_state SET fired_at = ?, snoozed_to = NULL
WHERE id = ? AND snoozed_to IS NOT NULL
`

type RefireDefaultAlarmStateParams struct {
	FiredAt *string
	ID      int64
}

// The same atomic refire claim as RefireAlarmState.
func (q *Queries) RefireDefaultAlarmState(ctx context.Context, arg RefireDefaultAlarmStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refireDefaultAlarmState, arg.FiredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const snoozeDefaultAlarmState = `-- name: SnoozeDefaultAlarmState :exec
UPDATE default_alarm_state SET snoozed_to = ? WHERE id = ?
`

type SnoozeDefaultAlarmStateParams struct {
	SnoozedTo *string
	ID        int64
}

func (q *Queries) SnoozeDefaultAlarmState(ctx context.Context, arg SnoozeDefaultAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, snoozeDefaultAlarmState, arg.SnoozedTo, arg.ID)
	return err
}
