// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_categories.sql

package storage

import (
	"context"
)

const createEventCategory = `-- name: CreateEventCategory :one
INSERT INTO event_categories (event_id, category) VALUES (?, ?) RETURNING event_id, category
`

type CreateEventCategoryParams struct {
	EventID  int64
	Category string
}

func (q *Queries) CreateEventCategory(ctx context.Context, arg CreateEventCategoryParams) (EventCategory, error) {
	row := q.db.QueryRowContext(ctx, createEventCategory, arg.EventID, arg.Category)
	var i EventCategory
	err := row.Scan(&i.EventID, &i.Category)
	return i, err
}

const deleteCategoriesByEventID = `-- name: DeleteCategoriesByEventID :exec
DELETE FROM event_categories WHERE event_id = ?
`

func (q *Queries) DeleteCategoriesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategoriesByEventID, eventID)
	return err
}

const listAllEventCategories = `-- name: ListAllEventCategories :many
SELECT DISTINCT category FROM event_categories ORDER BY category
`

func (q *Queries) ListAllEventCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllEventCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEventCategoriesWithIDs = `-- name: ListAllEventCategoriesWithIDs :many
SELECT event_id, category FROM event_categories ORDER BY event_id, category
`

func (q *Queries) ListAllEventCategoriesWithIDs(ctx context.Context) ([]EventCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAllEventCategoriesWithIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(&i.EventID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByEventID = `-- name: ListCategoriesByEventID :many
SELECT event_id, category FROM event_categories WHERE event_id = ? ORDER BY category
`

func (q *Queries) ListCategoriesByEventID(ctx context.Context, eventID int64) ([]EventCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(&i.EventID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
