// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package storage

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at
`

type CreateEventParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByUID = `-- name: GetEventByUID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at FROM events WHERE uid = ?
`

func (q *Queries) GetEventByUID(ctx context.Context, uid string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUID, uid)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByCalendarAndDateRange = `-- name: ListEventsByCalendarAndDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at FROM events WHERE calendar_id = ? AND start_time >= ? AND start_time < ? ORDER BY start_time
`

type ListEventsByCalendarAndDateRangeParams struct {
	CalendarID  int64
	StartTime   string
	StartTime_2 string
}

func (q *Queries) ListEventsByCalendarAndDateRange(ctx context.Context, arg ListEventsByCalendarAndDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByCalendarAndDateRange, arg.CalendarID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at FROM events WHERE start_time >= ? AND start_time < ? ORDER BY start_time
`

type ListEventsByDateRangeParams struct {
	StartTime   string
	StartTime_2 string
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByDateRange, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = ?, description = ?, location = ?,
    start_time = ?, end_time = ?, all_day = ?,
    recurrence_rule = ?, calendar_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at
`

type UpdateEventParams struct {
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
	CalendarID     int64
	ID             int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.CalendarID,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventByUID = `-- name: UpsertEventByUID :one
INSERT INTO events (uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uid) DO UPDATE SET
    title = excluded.title, description = excluded.description,
    location = excluded.location, start_time = excluded.start_time,
    end_time = excluded.end_time, all_day = excluded.all_day,
    recurrence_rule = excluded.recurrence_rule,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, created_at, updated_at
`

type UpsertEventByUIDParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
}

func (q *Queries) UpsertEventByUID(ctx context.Context, arg UpsertEventByUIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertEventByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
