// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_resources.sql

package storage

import (
	"context"
)

const createEventResource = `-- name: CreateEventResource :one
INSERT INTO event_resources (event_id, text) VALUES (?, ?) RETURNING id, event_id, text
`

type CreateEventResourceParams struct {
	EventID int64
	Text    string
}

func (q *Queries) CreateEventResource(ctx context.Context, arg CreateEventResourceParams) (EventResource, error) {
	row := q.db.QueryRowContext(ctx, createEventResource, arg.EventID, arg.Text)
	var i EventResource
	err := row.Scan(&i.ID, &i.EventID, &i.Text)
	return i, err
}

const deleteEventResourcesByEventID = `-- name: DeleteEventResourcesByEventID :exec
DELETE FROM event_resources WHERE event_id = ?
`

func (q *Queries) DeleteEventResourcesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventResourcesByEventID, eventID)
	return err
}

const listEventResourcesByEventID = `-- name: ListEventResourcesByEventID :many
SELECT id, event_id, text FROM event_resources WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListEventResourcesByEventID(ctx context.Context, eventID int64) ([]EventResource, error) {
	rows, err := q.db.QueryContext(ctx, listEventResourcesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventResource
	for rows.Next() {
		var i EventResource
		if err := rows.Scan(&i.ID, &i.EventID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
