// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_relations.sql

package storage

import (
	"context"
)

const createEventRelation = `-- name: CreateEventRelation :one
INSERT INTO event_relations (event_id, rel_type, rel_uid) VALUES (?, ?, ?) RETURNING id, event_id, rel_type, rel_uid
`

type CreateEventRelationParams struct {
	EventID int64
	RelType string
	RelUid  string
}

func (q *Queries) CreateEventRelation(ctx context.Context, arg CreateEventRelationParams) (EventRelation, error) {
	row := q.db.QueryRowContext(ctx, createEventRelation, arg.EventID, arg.RelType, arg.RelUid)
	var i EventRelation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.RelType,
		&i.RelUid,
	)
	return i, err
}

const deleteEventRelationsByEventID = `-- name: DeleteEventRelationsByEventID :exec
DELETE FROM event_relations WHERE event_id = ?
`

func (q *Queries) DeleteEventRelationsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventRelationsByEventID, eventID)
	return err
}

const listEventRelationsByEventID = `-- name: ListEventRelationsByEventID :many
SELECT id, event_id, rel_type, rel_uid FROM event_relations WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListEventRelationsByEventID(ctx context.Context, eventID int64) ([]EventRelation, error) {
	rows, err := q.db.QueryContext(ctx, listEventRelationsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRelation
	for rows.Next() {
		var i EventRelation
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.RelType,
			&i.RelUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
