// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_attachments.sql

package storage

import (
	"context"
)

const createEventAttachment = `-- name: CreateEventAttachment :one
INSERT INTO event_attachments (event_id, uri, fmttype, data, filename) VALUES (?, ?, ?, ?, ?) RETURNING id, event_id, uri, fmttype, data, filename
`

type CreateEventAttachmentParams struct {
	EventID  int64
	Uri      string
	Fmttype  *string
	Data     []byte
	Filename *string
}

func (q *Queries) CreateEventAttachment(ctx context.Context, arg CreateEventAttachmentParams) (EventAttachment, error) {
	row := q.db.QueryRowContext(ctx, createEventAttachment,
		arg.EventID,
		arg.Uri,
		arg.Fmttype,
		arg.Data,
		arg.Filename,
	)
	var i EventAttachment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const deleteEventAttachmentsByEventID = `-- name: DeleteEventAttachmentsByEventID :exec
DELETE FROM event_attachments WHERE event_id = ?
`

func (q *Queries) DeleteEventAttachmentsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventAttachmentsByEventID, eventID)
	return err
}

const getEventAttachment = `-- name: GetEventAttachment :one
SELECT id, event_id, uri, fmttype, data, filename FROM event_attachments WHERE id = ?
`

func (q *Queries) GetEventAttachment(ctx context.Context, id int64) (EventAttachment, error) {
	row := q.db.QueryRowContext(ctx, getEventAttachment, id)
	var i EventAttachment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const listEventAttachmentsByEventID = `-- name: ListEventAttachmentsByEventID :many
SELECT id, event_id, uri, fmttype, data, filename FROM event_attachments WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListEventAttachmentsByEventID(ctx context.Context, eventID int64) ([]EventAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listEventAttachmentsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAttachment
	for rows.Next() {
		var i EventAttachment
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Uri,
			&i.Fmttype,
			&i.Data,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
