// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_contacts.sql

package storage

import (
	"context"
)

const createEventContact = `-- name: CreateEventContact :one
INSERT INTO event_contacts (event_id, text) VALUES (?, ?) RETURNING id, event_id, text
`

type CreateEventContactParams struct {
	EventID int64
	Text    string
}

func (q *Queries) CreateEventContact(ctx context.Context, arg CreateEventContactParams) (EventContact, error) {
	row := q.db.QueryRowContext(ctx, createEventContact, arg.EventID, arg.Text)
	var i EventContact
	err := row.Scan(&i.ID, &i.EventID, &i.Text)
	return i, err
}

const deleteEventContactsByEventID = `-- name: DeleteEventContactsByEventID :exec
DELETE FROM event_contacts WHERE event_id = ?
`

func (q *Queries) DeleteEventContactsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventContactsByEventID, eventID)
	return err
}

const listEventContactsByEventID = `-- name: ListEventContactsByEventID :many
SELECT id, event_id, text FROM event_contacts WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListEventContactsByEventID(ctx context.Context, eventID int64) ([]EventContact, error) {
	rows, err := q.db.QueryContext(ctx, listEventContactsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventContact
	for rows.Next() {
		var i EventContact
		if err := rows.Scan(&i.ID, &i.EventID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
