// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package storage

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    uid, calendar_id, title, description, location,
    start_time, end_time, all_day, recurrence_rule,
    timezone, status, transp, sequence, priority,
    class, url, exdates, rdates, recurrence_id, geo
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at
`

type CreateEventParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
	Timezone       string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            string
	Exdates        string
	Rdates         string
	RecurrenceID   string
	Geo            string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Sequence,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByUID = `-- name: GetEventByUID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE uid = ? AND recurrence_id = ''
`

func (q *Queries) GetEventByUID(ctx context.Context, uid string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUID, uid)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByUIDAndRecurrenceID = `-- name: GetEventByUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE uid = ? AND recurrence_id = ?
`

type GetEventByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetEventByUIDAndRecurrenceID(ctx context.Context, arg GetEventByUIDAndRecurrenceIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events
`

func (q *Queries) ListAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCalendarAndDateRange = `-- name: ListEventsByCalendarAndDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE calendar_id = ? AND start_time >= ? AND start_time < ? ORDER BY start_time
`

type ListEventsByCalendarAndDateRangeParams struct {
	CalendarID  int64
	StartTime   string
	StartTime_2 string
}

func (q *Queries) ListEventsByCalendarAndDateRange(ctx context.Context, arg ListEventsByCalendarAndDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByCalendarAndDateRange, arg.CalendarID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE start_time >= ? AND start_time < ? ORDER BY start_time
`

type ListEventsByDateRangeParams struct {
	StartTime   string
	StartTime_2 string
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByDateRange, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByStatusAndDateRange = `-- name: ListEventsByStatusAndDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE status = ? AND start_time >= ? AND start_time < ? ORDER BY start_time
`

type ListEventsByStatusAndDateRangeParams struct {
	Status      string
	StartTime   string
	StartTime_2 string
}

func (q *Queries) ListEventsByStatusAndDateRange(ctx context.Context, arg ListEventsByStatusAndDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByStatusAndDateRange, arg.Status, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsFiltered = `-- name: ListEventsFiltered :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events
WHERE recurrence_rule = '' AND recurrence_id = ''
AND (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR status = ?2)
AND (?3 = '' OR start_time >= ?3)
AND (?4 = '' OR start_time < ?4)
ORDER BY start_time ASC
`

type ListEventsFilteredParams struct {
	CalendarID   interface{}
	FilterStatus interface{}
	FromTime     interface{}
	ToTime       interface{}
}

func (q *Queries) ListEventsFiltered(ctx context.Context, arg ListEventsFilteredParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsFiltered,
		arg.CalendarID,
		arg.FilterStatus,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForExport = `-- name: ListEventsForExport :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events
WHERE (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR start_time >= ?2)
AND (?3 = '' OR start_time < ?3)
AND (?4 = '' OR EXISTS (SELECT 1 FROM event_categories ec WHERE ec.event_id = events.id AND ec.category = ?4))
AND (?5 = '' OR status = ?5)
ORDER BY start_time ASC
`

type ListEventsForExportParams struct {
	CalendarID   interface{}
	FromTime     interface{}
	ToTime       interface{}
	Category     interface{}
	FilterStatus interface{}
}

func (q *Queries) ListEventsForExport(ctx context.Context, arg ListEventsForExportParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForExport,
		arg.CalendarID,
		arg.FromTime,
		arg.ToTime,
		arg.Category,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesByUID = `-- name: ListOverridesByUID :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE uid = ? AND recurrence_id != '' ORDER BY recurrence_id
`

func (q *Queries) ListOverridesByUID(ctx context.Context, uid string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listOverridesByUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringEvents = `-- name: ListRecurringEvents :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE recurrence_rule != '' AND recurrence_id = ''
`

func (q *Queries) ListRecurringEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringEventsByCalendar = `-- name: ListRecurringEventsByCalendar :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE recurrence_rule != '' AND recurrence_id = '' AND calendar_id = ?
`

func (q *Queries) ListRecurringEventsByCalendar(ctx context.Context, calendarID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringEventsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringEventsByStatus = `-- name: ListRecurringEventsByStatus :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events WHERE recurrence_rule != '' AND recurrence_id = '' AND status = ?
`

func (q *Queries) ListRecurringEventsByStatus(ctx context.Context, status string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringEventsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringEventsFiltered = `-- name: ListRecurringEventsFiltered :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at FROM events
WHERE recurrence_rule != '' AND recurrence_id = ''
AND (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR status = ?2)
AND (?3 = '' OR EXISTS (SELECT 1 FROM event_categories ec WHERE ec.event_id = events.id AND ec.category = ?3))
ORDER BY start_time ASC
`

type ListRecurringEventsFilteredParams struct {
	CalendarID   interface{}
	FilterStatus interface{}
	Category     interface{}
}

func (q *Queries) ListRecurringEventsFiltered(ctx context.Context, arg ListRecurringEventsFilteredParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringEventsFiltered, arg.CalendarID, arg.FilterStatus, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = ?, description = ?, location = ?,
    start_time = ?, end_time = ?, all_day = ?,
    recurrence_rule = ?, calendar_id = ?,
    timezone = ?, status = ?, transp = ?,
    sequence = sequence + 1, priority = ?,
    class = ?, url = ?,
    exdates = ?, rdates = ?, geo = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at
`

type UpdateEventParams struct {
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
	CalendarID     int64
	Timezone       string
	Status         string
	Transp         string
	Priority       int64
	Class          string
	Url            string
	Exdates        string
	Rdates         string
	Geo            string
	ID             int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.CalendarID,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.Geo,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventByUID = `-- name: UpsertEventByUID :one
INSERT INTO events (
    uid, calendar_id, title, description, location,
    start_time, end_time, all_day, recurrence_rule,
    timezone, status, transp, sequence, priority,
    class, url, exdates, rdates, recurrence_id, geo
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    title = excluded.title, description = excluded.description,
    location = excluded.location, start_time = excluded.start_time,
    end_time = excluded.end_time, all_day = excluded.all_day,
    recurrence_rule = excluded.recurrence_rule,
    timezone = excluded.timezone, status = excluded.status,
    transp = excluded.transp,
    sequence = MAX(excluded.sequence, events.sequence + 1),
    priority = excluded.priority, class = excluded.class,
    url = excluded.url,
    exdates = excluded.exdates, rdates = excluded.rdates,
    geo = excluded.geo,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at
`

type UpsertEventByUIDParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
	Timezone       string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            string
	Exdates        string
	Rdates         string
	RecurrenceID   string
	Geo            string
}

func (q *Queries) UpsertEventByUID(ctx context.Context, arg UpsertEventByUIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertEventByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Sequence,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
