// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_comments.sql

package storage

import (
	"context"
)

const createEventComment = `-- name: CreateEventComment :one
INSERT INTO event_comments (event_id, text) VALUES (?, ?) RETURNING id, event_id, text
`

type CreateEventCommentParams struct {
	EventID int64
	Text    string
}

func (q *Queries) CreateEventComment(ctx context.Context, arg CreateEventCommentParams) (EventComment, error) {
	row := q.db.QueryRowContext(ctx, createEventComment, arg.EventID, arg.Text)
	var i EventComment
	err := row.Scan(&i.ID, &i.EventID, &i.Text)
	return i, err
}

const deleteEventCommentsByEventID = `-- name: DeleteEventCommentsByEventID :exec
DELETE FROM event_comments WHERE event_id = ?
`

func (q *Queries) DeleteEventCommentsByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventCommentsByEventID, eventID)
	return err
}

const listEventCommentsByEventID = `-- name: ListEventCommentsByEventID :many
SELECT id, event_id, text FROM event_comments WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListEventCommentsByEventID(ctx context.Context, eventID int64) ([]EventComment, error) {
	rows, err := q.db.QueryContext(ctx, listEventCommentsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventComment
	for rows.Next() {
		var i EventComment
		if err := rows.Scan(&i.ID, &i.EventID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
