// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_attachments.sql

package storage

import (
	"context"
)

const createJournalAttachment = `-- name: CreateJournalAttachment :one
INSERT INTO journal_attachments (journal_id, uri, fmttype, data, filename) VALUES (?, ?, ?, ?, ?) RETURNING id, journal_id, uri, fmttype, data, filename
`

type CreateJournalAttachmentParams struct {
	JournalID int64
	Uri       *string
	Fmttype   *string
	Data      []byte
	Filename  *string
}

func (q *Queries) CreateJournalAttachment(ctx context.Context, arg CreateJournalAttachmentParams) (JournalAttachment, error) {
	row := q.db.QueryRowContext(ctx, createJournalAttachment,
		arg.JournalID,
		arg.Uri,
		arg.Fmttype,
		arg.Data,
		arg.Filename,
	)
	var i JournalAttachment
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const deleteJournalAttachmentsByJournalID = `-- name: DeleteJournalAttachmentsByJournalID :exec
DELETE FROM journal_attachments WHERE journal_id = ?
`

func (q *Queries) DeleteJournalAttachmentsByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalAttachmentsByJournalID, journalID)
	return err
}

const getJournalAttachment = `-- name: GetJournalAttachment :one
SELECT id, journal_id, uri, fmttype, data, filename FROM journal_attachments WHERE id = ?
`

func (q *Queries) GetJournalAttachment(ctx context.Context, id int64) (JournalAttachment, error) {
	row := q.db.QueryRowContext(ctx, getJournalAttachment, id)
	var i JournalAttachment
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const listJournalAttachmentsByJournalID = `-- name: ListJournalAttachmentsByJournalID :many
SELECT id, journal_id, uri, fmttype, data, filename FROM journal_attachments WHERE journal_id = ? ORDER BY id
`

func (q *Queries) ListJournalAttachmentsByJournalID(ctx context.Context, journalID int64) ([]JournalAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listJournalAttachmentsByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalAttachment
	for rows.Next() {
		var i JournalAttachment
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.Uri,
			&i.Fmttype,
			&i.Data,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
