// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_comments.sql

package storage

import (
	"context"
)

const createJournalComment = `-- name: CreateJournalComment :one
INSERT INTO journal_comments (journal_id, text) VALUES (?, ?) RETURNING id, journal_id, text
`

type CreateJournalCommentParams struct {
	JournalID int64
	Text      string
}

func (q *Queries) CreateJournalComment(ctx context.Context, arg CreateJournalCommentParams) (JournalComment, error) {
	row := q.db.QueryRowContext(ctx, createJournalComment, arg.JournalID, arg.Text)
	var i JournalComment
	err := row.Scan(&i.ID, &i.JournalID, &i.Text)
	return i, err
}

const deleteJournalCommentsByJournalID = `-- name: DeleteJournalCommentsByJournalID :exec
DELETE FROM journal_comments WHERE journal_id = ?
`

func (q *Queries) DeleteJournalCommentsByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalCommentsByJournalID, journalID)
	return err
}

const listJournalCommentsByJournalID = `-- name: ListJournalCommentsByJournalID :many
SELECT id, journal_id, text FROM journal_comments WHERE journal_id = ? ORDER BY id
`

func (q *Queries) ListJournalCommentsByJournalID(ctx context.Context, journalID int64) ([]JournalComment, error) {
	rows, err := q.db.QueryContext(ctx, listJournalCommentsByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalComment
	for rows.Next() {
		var i JournalComment
		if err := rows.Scan(&i.ID, &i.JournalID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
