// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_categories.sql

package storage

import (
	"context"
)

const createJournalCategory = `-- name: CreateJournalCategory :one
INSERT INTO journal_categories (journal_id, category) VALUES (?, ?) RETURNING journal_id, category
`

type CreateJournalCategoryParams struct {
	JournalID int64
	Category  string
}

func (q *Queries) CreateJournalCategory(ctx context.Context, arg CreateJournalCategoryParams) (JournalCategory, error) {
	row := q.db.QueryRowContext(ctx, createJournalCategory, arg.JournalID, arg.Category)
	var i JournalCategory
	err := row.Scan(&i.JournalID, &i.Category)
	return i, err
}

const deleteCategoriesByJournalID = `-- name: DeleteCategoriesByJournalID :exec
DELETE FROM journal_categories WHERE journal_id = ?
`

func (q *Queries) DeleteCategoriesByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategoriesByJournalID, journalID)
	return err
}

const listAllJournalCategories = `-- name: ListAllJournalCategories :many
SELECT DISTINCT category FROM journal_categories ORDER BY category
`

func (q *Queries) ListAllJournalCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllJournalCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByJournalID = `-- name: ListCategoriesByJournalID :many
SELECT journal_id, category FROM journal_categories WHERE journal_id = ? ORDER BY category
`

func (q *Queries) ListCategoriesByJournalID(ctx context.Context, journalID int64) ([]JournalCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalCategory
	for rows.Next() {
		var i JournalCategory
		if err := rows.Scan(&i.JournalID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
