// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_attendees.sql

package storage

import (
	"context"
)

const createJournalAttendee = `-- name: CreateJournalAttendee :one
INSERT INTO journal_attendees (journal_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, journal_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language
`

type CreateJournalAttendeeParams struct {
	JournalID     int64
	Email         string
	Name          *string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        *string
	Rsvp          *string
	SentBy        *string
	DelegatedTo   *string
	DelegatedFrom *string
	Member        *string
	Dir           *string
	Language      *string
}

func (q *Queries) CreateJournalAttendee(ctx context.Context, arg CreateJournalAttendeeParams) (JournalAttendee, error) {
	row := q.db.QueryRowContext(ctx, createJournalAttendee,
		arg.JournalID,
		arg.Email,
		arg.Name,
		arg.RsvpStatus,
		arg.Role,
		arg.Organizer,
		arg.Cutype,
		arg.Rsvp,
		arg.SentBy,
		arg.DelegatedTo,
		arg.DelegatedFrom,
		arg.Member,
		arg.Dir,
		arg.Language,
	)
	var i JournalAttendee
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Email,
		&i.Name,
		&i.RsvpStatus,
		&i.Role,
		&i.Organizer,
		&i.Cutype,
		&i.Rsvp,
		&i.SentBy,
		&i.DelegatedTo,
		&i.DelegatedFrom,
		&i.Member,
		&i.Dir,
		&i.Language,
	)
	return i, err
}

const deleteJournalAttendeesByJournalID = `-- name: DeleteJournalAttendeesByJournalID :exec
DELETE FROM journal_attendees WHERE journal_id = ?
`

func (q *Queries) DeleteJournalAttendeesByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalAttendeesByJournalID, journalID)
	return err
}

const listJournalAttendeesByJournalID = `-- name: ListJournalAttendeesByJournalID :many
SELECT id, journal_id, email, name, rsvp_status, role, organizer, cutype, rsvp, sent_by, delegated_to, delegated_from, member, dir, language FROM journal_attendees WHERE journal_id = ? ORDER BY organizer DESC, name
`

func (q *Queries) ListJournalAttendeesByJournalID(ctx context.Context, journalID int64) ([]JournalAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listJournalAttendeesByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalAttendee
	for rows.Next() {
		var i JournalAttendee
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.Email,
			&i.Name,
			&i.RsvpStatus,
			&i.Role,
			&i.Organizer,
			&i.Cutype,
			&i.Rsvp,
			&i.SentBy,
			&i.DelegatedTo,
			&i.DelegatedFrom,
			&i.Member,
			&i.Dir,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
