// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_contacts.sql

package storage

import (
	"context"
)

const createJournalContact = `-- name: CreateJournalContact :one
INSERT INTO journal_contacts (journal_id, text) VALUES (?, ?) RETURNING id, journal_id, text
`

type CreateJournalContactParams struct {
	JournalID int64
	Text      string
}

func (q *Queries) CreateJournalContact(ctx context.Context, arg CreateJournalContactParams) (JournalContact, error) {
	row := q.db.QueryRowContext(ctx, createJournalContact, arg.JournalID, arg.Text)
	var i JournalContact
	err := row.Scan(&i.ID, &i.JournalID, &i.Text)
	return i, err
}

const deleteJournalContactsByJournalID = `-- name: DeleteJournalContactsByJournalID :exec
DELETE FROM journal_contacts WHERE journal_id = ?
`

func (q *Queries) DeleteJournalContactsByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalContactsByJournalID, journalID)
	return err
}

const listJournalContactsByJournalID = `-- name: ListJournalContactsByJournalID :many
SELECT id, journal_id, text FROM journal_contacts WHERE journal_id = ? ORDER BY id
`

func (q *Queries) ListJournalContactsByJournalID(ctx context.Context, journalID int64) ([]JournalContact, error) {
	rows, err := q.db.QueryContext(ctx, listJournalContactsByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalContact
	for rows.Next() {
		var i JournalContact
		if err := rows.Scan(&i.ID, &i.JournalID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
