// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_exdate_deletes.sql

package storage

import (
	"context"
)

const deleteJournalExdateDelete = `-- name: DeleteJournalExdateDelete :exec
DELETE FROM journal_exdate_deletes WHERE id = ?
`

func (q *Queries) DeleteJournalExdateDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalExdateDelete, id)
	return err
}

const getJournalExdateDeleteByUIDRecurrence = `-- name: GetJournalExdateDeleteByUIDRecurrence :one
SELECT id, calendar_id, uid, recurrence_id, deleted_at FROM journal_exdate_deletes WHERE uid = ? AND recurrence_id = ?
`

type GetJournalExdateDeleteByUIDRecurrenceParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetJournalExdateDeleteByUIDRecurrence(ctx context.Context, arg GetJournalExdateDeleteByUIDRecurrenceParams) (JournalExdateDelete, error) {
	row := q.db.QueryRowContext(ctx, getJournalExdateDeleteByUIDRecurrence, arg.Uid, arg.RecurrenceID)
	var i JournalExdateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.RecurrenceID,
		&i.DeletedAt,
	)
	return i, err
}

const purgeOldJournalExdateDeletes = `-- name: PurgeOldJournalExdateDeletes :execrows
DELETE FROM journal_exdate_deletes WHERE deleted_at < ?
`

func (q *Queries) PurgeOldJournalExdateDeletes(ctx context.Context, deletedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldJournalExdateDeletes, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordJournalExdateDelete = `-- name: RecordJournalExdateDelete :exec
INSERT INTO journal_exdate_deletes (calendar_id, uid, recurrence_id)
VALUES (?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type RecordJournalExdateDeleteParams struct {
	CalendarID   int64
	Uid          string
	RecurrenceID string
}

// Idempotent: deleting the same instance twice leaves exactly one log row.
func (q *Queries) RecordJournalExdateDelete(ctx context.Context, arg RecordJournalExdateDeleteParams) error {
	_, err := q.db.ExecContext(ctx, recordJournalExdateDelete, arg.CalendarID, arg.Uid, arg.RecurrenceID)
	return err
}
