// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_relations.sql

package storage

import (
	"context"
)

const createJournalRelation = `-- name: CreateJournalRelation :one
INSERT INTO journal_relations (journal_id, rel_type, rel_uid) VALUES (?, ?, ?) RETURNING id, journal_id, rel_type, rel_uid
`

type CreateJournalRelationParams struct {
	JournalID int64
	RelType   string
	RelUid    string
}

func (q *Queries) CreateJournalRelation(ctx context.Context, arg CreateJournalRelationParams) (JournalRelation, error) {
	row := q.db.QueryRowContext(ctx, createJournalRelation, arg.JournalID, arg.RelType, arg.RelUid)
	var i JournalRelation
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.RelType,
		&i.RelUid,
	)
	return i, err
}

const deleteJournalRelationsByJournalID = `-- name: DeleteJournalRelationsByJournalID :exec
DELETE FROM journal_relations WHERE journal_id = ?
`

func (q *Queries) DeleteJournalRelationsByJournalID(ctx context.Context, journalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalRelationsByJournalID, journalID)
	return err
}

const listJournalRelationsByJournalID = `-- name: ListJournalRelationsByJournalID :many
SELECT id, journal_id, rel_type, rel_uid FROM journal_relations WHERE journal_id = ? ORDER BY id
`

func (q *Queries) ListJournalRelationsByJournalID(ctx context.Context, journalID int64) ([]JournalRelation, error) {
	rows, err := q.db.QueryContext(ctx, listJournalRelationsByJournalID, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalRelation
	for rows.Next() {
		var i JournalRelation
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.RelType,
			&i.RelUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
