// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type AlarmState struct {
	ID        int64
	AlarmID   int64
	EventID   int64
	TriggerAt string
	FiredAt   sql.NullString
	AckedAt   sql.NullString
	SnoozedTo sql.NullString
}

type AllAlarmState struct {
	Type      string
	ID        int64
	AlarmID   int64
	ItemID    int64
	TriggerAt string
	FiredAt   sql.NullString
	AckedAt   sql.NullString
	SnoozedTo sql.NullString
}

type Calendar struct {
	ID          int64
	Name        string
	Color       string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type Event struct {
	ID             int64
	Uid            string
	CalendarID     int64
	Title          string
	Description    string
	Location       string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule string
	Timezone       string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            string
	Exdates        string
	Rdates         string
	RecurrenceID   string
	Geo            string
	CreatedAt      string
	UpdatedAt      string
	Duration       string
	Dtstamp        string
}

type EventAlarm struct {
	ID            int64
	EventID       int64
	Action        string
	TriggerValue  string
	Description   string
	Repeat        int64
	Duration      string
	Related       string
	Summary       string
	Uid           string
	Acknowledged  string
	AttachUri     string
	AttachFmttype string
}

type EventAlarmAttendee struct {
	ID      int64
	AlarmID int64
	Email   string
	Name    string
}

type EventAttachment struct {
	ID       int64
	EventID  int64
	Uri      string
	Fmttype  string
	Data     []byte
	Filename string
}

type EventAttendee struct {
	ID            int64
	EventID       int64
	Email         string
	Name          string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        string
	Rsvp          string
	SentBy        string
	DelegatedTo   string
	DelegatedFrom string
	Member        string
	Dir           string
	Language      string
}

type EventCategory struct {
	EventID  int64
	Category string
}

type EventComment struct {
	ID      int64
	EventID int64
	Text    string
}

type EventContact struct {
	ID      int64
	EventID int64
	Text    string
}

type EventRelation struct {
	ID      int64
	EventID int64
	RelType string
	RelUid  string
}

type EventResource struct {
	ID      int64
	EventID int64
	Text    string
}

type RecurrenceInstance struct {
	ID         int64
	EventID    int64
	OriginalID int64
	InstanceAt string
	IsOverride int64
	CreatedAt  string
}

type Timezone struct {
	Tzid          string
	VtimezoneData string
	CreatedAt     string
}

type Todo struct {
	ID              int64
	Uid             string
	CalendarID      int64
	Summary         string
	Description     string
	Location        string
	DueDate         string
	StartDate       string
	Duration        string
	CompletedAt     string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             string
	RecurrenceRule  string
	Timezone        string
	Sequence        int64
	Exdates         string
	Rdates          string
	RecurrenceID    string
	Geo             string
	CreatedAt       string
	UpdatedAt       string
	Dtstamp         string
}

type TodoAlarm struct {
	ID            int64
	TodoID        int64
	Action        string
	TriggerValue  string
	Description   string
	Repeat        int64
	Duration      string
	Related       string
	Summary       string
	Uid           string
	Acknowledged  string
	AttachUri     string
	AttachFmttype string
}

type TodoAlarmAttendee struct {
	ID      int64
	AlarmID int64
	Email   string
	Name    string
}

type TodoAlarmState struct {
	ID        int64
	AlarmID   int64
	TodoID    int64
	TriggerAt string
	FiredAt   sql.NullString
	AckedAt   sql.NullString
	SnoozedTo sql.NullString
}

type TodoAttachment struct {
	ID       int64
	TodoID   int64
	Uri      string
	Fmttype  string
	Data     []byte
	Filename string
}

type TodoAttendee struct {
	ID            int64
	TodoID        int64
	Email         string
	Name          string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        string
	Rsvp          string
	SentBy        string
	DelegatedTo   string
	DelegatedFrom string
	Member        string
	Dir           string
	Language      string
}

type TodoCategory struct {
	TodoID   int64
	Category string
}

type TodoComment struct {
	ID     int64
	TodoID int64
	Text   string
}

type TodoContact struct {
	ID     int64
	TodoID int64
	Text   string
}

type TodoRecurrenceInstance struct {
	ID         int64
	TodoID     int64
	OriginalID int64
	InstanceAt string
	IsOverride int64
	CreatedAt  string
}

type TodoRelation struct {
	ID      int64
	TodoID  int64
	RelType string
	RelUid  string
}

type TodoResource struct {
	ID     int64
	TodoID int64
	Text   string
}
