// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurrence.sql

package storage

import (
	"context"
)

const countRecurrenceInstances = `-- name: CountRecurrenceInstances :one
SELECT COUNT(*) FROM recurrence_instances WHERE event_id = ?
`

func (q *Queries) CountRecurrenceInstances(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecurrenceInstances, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecurrenceInstances = `-- name: DeleteRecurrenceInstances :exec
DELETE FROM recurrence_instances WHERE event_id = ? AND instance_at >= ?
`

type DeleteRecurrenceInstancesParams struct {
	EventID    int64
	InstanceAt string
}

func (q *Queries) DeleteRecurrenceInstances(ctx context.Context, arg DeleteRecurrenceInstancesParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecurrenceInstances, arg.EventID, arg.InstanceAt)
	return err
}

const deleteTodoRecurrenceInstances = `-- name: DeleteTodoRecurrenceInstances :exec
DELETE FROM todo_recurrence_instances WHERE todo_id = ? AND instance_at >= ?
`

type DeleteTodoRecurrenceInstancesParams struct {
	TodoID     int64
	InstanceAt string
}

func (q *Queries) DeleteTodoRecurrenceInstances(ctx context.Context, arg DeleteTodoRecurrenceInstancesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodoRecurrenceInstances, arg.TodoID, arg.InstanceAt)
	return err
}

const insertRecurrenceInstance = `-- name: InsertRecurrenceInstance :one
INSERT INTO recurrence_instances (event_id, original_id, instance_at, is_override)
VALUES (?, ?, ?, ?)
ON CONFLICT(event_id, instance_at) DO NOTHING
RETURNING id, event_id, original_id, instance_at, is_override, created_at
`

type InsertRecurrenceInstanceParams struct {
	EventID    int64
	OriginalID int64
	InstanceAt string
	IsOverride int64
}

func (q *Queries) InsertRecurrenceInstance(ctx context.Context, arg InsertRecurrenceInstanceParams) (RecurrenceInstance, error) {
	row := q.db.QueryRowContext(ctx, insertRecurrenceInstance,
		arg.EventID,
		arg.OriginalID,
		arg.InstanceAt,
		arg.IsOverride,
	)
	var i RecurrenceInstance
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OriginalID,
		&i.InstanceAt,
		&i.IsOverride,
		&i.CreatedAt,
	)
	return i, err
}

const insertTodoRecurrenceInstance = `-- name: InsertTodoRecurrenceInstance :one
INSERT INTO todo_recurrence_instances (todo_id, original_id, instance_at, is_override)
VALUES (?, ?, ?, ?)
ON CONFLICT(todo_id, instance_at) DO NOTHING
RETURNING id, todo_id, original_id, instance_at, is_override, created_at
`

type InsertTodoRecurrenceInstanceParams struct {
	TodoID     int64
	OriginalID int64
	InstanceAt string
	IsOverride int64
}

// Same for todos
func (q *Queries) InsertTodoRecurrenceInstance(ctx context.Context, arg InsertTodoRecurrenceInstanceParams) (TodoRecurrenceInstance, error) {
	row := q.db.QueryRowContext(ctx, insertTodoRecurrenceInstance,
		arg.TodoID,
		arg.OriginalID,
		arg.InstanceAt,
		arg.IsOverride,
	)
	var i TodoRecurrenceInstance
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.OriginalID,
		&i.InstanceAt,
		&i.IsOverride,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurrenceInstances = `-- name: ListRecurrenceInstances :many
SELECT id, event_id, original_id, instance_at, is_override, created_at FROM recurrence_instances 
WHERE event_id = ? AND instance_at >= ? AND instance_at < ?
ORDER BY instance_at
`

type ListRecurrenceInstancesParams struct {
	EventID      int64
	InstanceAt   string
	InstanceAt_2 string
}

func (q *Queries) ListRecurrenceInstances(ctx context.Context, arg ListRecurrenceInstancesParams) ([]RecurrenceInstance, error) {
	rows, err := q.db.QueryContext(ctx, listRecurrenceInstances, arg.EventID, arg.InstanceAt, arg.InstanceAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurrenceInstance
	for rows.Next() {
		var i RecurrenceInstance
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OriginalID,
			&i.InstanceAt,
			&i.IsOverride,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoRecurrenceInstances = `-- name: ListTodoRecurrenceInstances :many
SELECT id, todo_id, original_id, instance_at, is_override, created_at FROM todo_recurrence_instances 
WHERE todo_id = ? AND instance_at >= ? AND instance_at < ?
ORDER BY instance_at
`

type ListTodoRecurrenceInstancesParams struct {
	TodoID       int64
	InstanceAt   string
	InstanceAt_2 string
}

func (q *Queries) ListTodoRecurrenceInstances(ctx context.Context, arg ListTodoRecurrenceInstancesParams) ([]TodoRecurrenceInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTodoRecurrenceInstances, arg.TodoID, arg.InstanceAt, arg.InstanceAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoRecurrenceInstance
	for rows.Next() {
		var i TodoRecurrenceInstance
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.OriginalID,
			&i.InstanceAt,
			&i.IsOverride,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
