// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package storage

import (
	"context"
)

const searchEvents = `-- name: SearchEvents :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp FROM events
WHERE (
    lower_unicode(title) LIKE '%' || lower_unicode(?1) || '%' OR
    lower_unicode(description) LIKE '%' || lower_unicode(?1) || '%' OR
    lower_unicode(location) LIKE '%' || lower_unicode(?1) || '%' OR
    EXISTS (SELECT 1 FROM event_categories ec WHERE ec.event_id = events.id AND lower_unicode(ec.category) LIKE '%' || lower_unicode(?1) || '%')
)
AND (?2 = 0 OR calendar_id = ?2)
AND (?3 = '' OR start_time >= ?3)
AND (?4 = '' OR start_time < ?4)
AND (?5 = '' OR status = ?5)
ORDER BY start_time ASC
`

type SearchEventsParams struct {
	Query        interface{}
	CalendarID   interface{}
	FromTime     interface{}
	ToTime       interface{}
	FilterStatus interface{}
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, searchEvents,
		arg.Query,
		arg.CalendarID,
		arg.FromTime,
		arg.ToTime,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodos = `-- name: SearchTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos
WHERE (
    lower_unicode(summary) LIKE '%' || lower_unicode(?1) || '%' OR
    lower_unicode(description) LIKE '%' || lower_unicode(?1) || '%' OR
    lower_unicode(location) LIKE '%' || lower_unicode(?1) || '%' OR
    EXISTS (SELECT 1 FROM todo_categories tc WHERE tc.todo_id = todos.id AND lower_unicode(tc.category) LIKE '%' || lower_unicode(?1) || '%')
)
AND (?2 = 0 OR calendar_id = ?2)
AND (?3 = '' OR status = ?3)
AND (?4 = 0 OR (?4 = 1 AND completed_at != '') OR (?4 = 2 AND completed_at = ''))
ORDER BY due_date ASC, summary ASC
`

type SearchTodosParams struct {
	Query           interface{}
	CalendarID      interface{}
	FilterStatus    interface{}
	CompletedFilter interface{}
}

func (q *Queries) SearchTodos(ctx context.Context, arg SearchTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, searchTodos,
		arg.Query,
		arg.CalendarID,
		arg.FilterStatus,
		arg.CompletedFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
