// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package storage

import (
	"context"
	"database/sql"
)

const searchEvents = `-- name: SearchEvents :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, created_at, updated_at, geo, categories FROM events_v
WHERE (
    title LIKE '%' || ?1 || '%' OR
    description LIKE '%' || ?1 || '%' OR
    location LIKE '%' || ?1 || '%' OR
    EXISTS (SELECT 1 FROM event_categories ec WHERE ec.event_id = events_v.id AND ec.category LIKE '%' || ?1 || '%')
)
AND (?2 = 0 OR calendar_id = ?2)
AND (?3 = '' OR start_time >= ?3)
AND (?4 = '' OR start_time < ?4)
AND (?5 = '' OR status = ?5)
ORDER BY start_time ASC
`

type SearchEventsParams struct {
	Query        sql.NullString
	CalendarID   interface{}
	FromTime     interface{}
	ToTime       interface{}
	FilterStatus interface{}
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]EventsV, error) {
	rows, err := q.db.QueryContext(ctx, searchEvents,
		arg.Query,
		arg.CalendarID,
		arg.FromTime,
		arg.ToTime,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsV
	for rows.Next() {
		var i EventsV
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Geo,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodos = `-- name: SearchTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, created_at, updated_at, geo, categories FROM todos_v
WHERE (
    summary LIKE '%' || ?1 || '%' OR
    description LIKE '%' || ?1 || '%' OR
    location LIKE '%' || ?1 || '%' OR
    EXISTS (SELECT 1 FROM todo_categories tc WHERE tc.todo_id = todos_v.id AND tc.category LIKE '%' || ?1 || '%')
)
AND (?2 = 0 OR calendar_id = ?2)
AND (?3 = '' OR status = ?3)
AND (?4 = 0 OR (?4 = 1 AND completed_at != '') OR (?4 = 2 AND completed_at = ''))
ORDER BY due_date ASC, summary ASC
`

type SearchTodosParams struct {
	Query           sql.NullString
	CalendarID      interface{}
	FilterStatus    interface{}
	CompletedFilter interface{}
}

func (q *Queries) SearchTodos(ctx context.Context, arg SearchTodosParams) ([]TodosV, error) {
	rows, err := q.db.QueryContext(ctx, searchTodos,
		arg.Query,
		arg.CalendarID,
		arg.FilterStatus,
		arg.CompletedFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodosV
	for rows.Next() {
		var i TodosV
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Geo,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
