// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_conflicts.sql

package storage

import (
	"context"
)

const countOpenSyncConflicts = `-- name: CountOpenSyncConflicts :one
SELECT COUNT(*) FROM sync_conflicts WHERE calendar_id = ? AND uid = ?
`

type CountOpenSyncConflictsParams struct {
	CalendarID int64
	Uid        string
}

func (q *Queries) CountOpenSyncConflicts(ctx context.Context, arg CountOpenSyncConflictsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenSyncConflicts, arg.CalendarID, arg.Uid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSyncConflict = `-- name: CreateSyncConflict :exec
INSERT INTO sync_conflicts (calendar_id, owner_type, owner_id, uid, local_ical, server_ical, server_etag)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(calendar_id, uid) DO UPDATE SET
    owner_type = excluded.owner_type,
    owner_id = excluded.owner_id,
    local_ical = excluded.local_ical,
    server_ical = excluded.server_ical,
    server_etag = excluded.server_etag,
    detected_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type CreateSyncConflictParams struct {
	CalendarID int64
	OwnerType  string
	OwnerID    int64
	Uid        string
	LocalIcal  string
	ServerIcal string
	ServerEtag string
}

func (q *Queries) CreateSyncConflict(ctx context.Context, arg CreateSyncConflictParams) error {
	_, err := q.db.ExecContext(ctx, createSyncConflict,
		arg.CalendarID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Uid,
		arg.LocalIcal,
		arg.ServerIcal,
		arg.ServerEtag,
	)
	return err
}

const deleteSyncConflict = `-- name: DeleteSyncConflict :exec
DELETE FROM sync_conflicts WHERE id = ?
`

func (q *Queries) DeleteSyncConflict(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSyncConflict, id)
	return err
}

const deleteSyncConflictsByCalendar = `-- name: DeleteSyncConflictsByCalendar :exec
DELETE FROM sync_conflicts WHERE calendar_id = ?
`

func (q *Queries) DeleteSyncConflictsByCalendar(ctx context.Context, calendarID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSyncConflictsByCalendar, calendarID)
	return err
}

const getSyncConflict = `-- name: GetSyncConflict :one
SELECT id, calendar_id, owner_type, owner_id, uid, local_ical, server_ical, server_etag, detected_at FROM sync_conflicts WHERE id = ?
`

func (q *Queries) GetSyncConflict(ctx context.Context, id int64) (SyncConflict, error) {
	row := q.db.QueryRowContext(ctx, getSyncConflict, id)
	var i SyncConflict
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Uid,
		&i.LocalIcal,
		&i.ServerIcal,
		&i.ServerEtag,
		&i.DetectedAt,
	)
	return i, err
}

const listSyncConflicts = `-- name: ListSyncConflicts :many
SELECT id, calendar_id, owner_type, owner_id, uid, local_ical, server_ical, server_etag, detected_at FROM sync_conflicts ORDER BY detected_at DESC
`

func (q *Queries) ListSyncConflicts(ctx context.Context) ([]SyncConflict, error) {
	rows, err := q.db.QueryContext(ctx, listSyncConflicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncConflict
	for rows.Next() {
		var i SyncConflict
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Uid,
			&i.LocalIcal,
			&i.ServerIcal,
			&i.ServerEtag,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncConflictsByCalendar = `-- name: ListSyncConflictsByCalendar :many
SELECT id, calendar_id, owner_type, owner_id, uid, local_ical, server_ical, server_etag, detected_at FROM sync_conflicts WHERE calendar_id = ? ORDER BY detected_at DESC
`

func (q *Queries) ListSyncConflictsByCalendar(ctx context.Context, calendarID int64) ([]SyncConflict, error) {
	rows, err := q.db.QueryContext(ctx, listSyncConflictsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncConflict
	for rows.Next() {
		var i SyncConflict
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Uid,
			&i.LocalIcal,
			&i.ServerIcal,
			&i.ServerEtag,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
