// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_resources.sql

package storage

import (
	"context"
)

const clearSyncResourceDirty = `-- name: ClearSyncResourceDirty :exec
UPDATE sync_resources SET dirty = 0, etag = ? WHERE calendar_id = ? AND uid = ?
`

type ClearSyncResourceDirtyParams struct {
	Etag       string
	CalendarID int64
	Uid        string
}

func (q *Queries) ClearSyncResourceDirty(ctx context.Context, arg ClearSyncResourceDirtyParams) error {
	_, err := q.db.ExecContext(ctx, clearSyncResourceDirty, arg.Etag, arg.CalendarID, arg.Uid)
	return err
}

const createTombstone = `-- name: CreateTombstone :exec
INSERT INTO tombstones (calendar_id, uid, remote_url) VALUES (?, ?, ?)
`

type CreateTombstoneParams struct {
	CalendarID int64
	Uid        string
	RemoteUrl  string
}

func (q *Queries) CreateTombstone(ctx context.Context, arg CreateTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, createTombstone, arg.CalendarID, arg.Uid, arg.RemoteUrl)
	return err
}

const deleteStaleTombstones = `-- name: DeleteStaleTombstones :exec
DELETE FROM tombstones WHERE deleted_at < strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-30 days')
`

func (q *Queries) DeleteStaleTombstones(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStaleTombstones)
	return err
}

const deleteSyncResource = `-- name: DeleteSyncResource :exec
DELETE FROM sync_resources WHERE calendar_id = ? AND uid = ?
`

type DeleteSyncResourceParams struct {
	CalendarID int64
	Uid        string
}

func (q *Queries) DeleteSyncResource(ctx context.Context, arg DeleteSyncResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteSyncResource, arg.CalendarID, arg.Uid)
	return err
}

const deleteSyncResourcesByCalendar = `-- name: DeleteSyncResourcesByCalendar :exec
DELETE FROM sync_resources WHERE calendar_id = ?
`

func (q *Queries) DeleteSyncResourcesByCalendar(ctx context.Context, calendarID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSyncResourcesByCalendar, calendarID)
	return err
}

const deleteTombstone = `-- name: DeleteTombstone :exec
DELETE FROM tombstones WHERE id = ?
`

func (q *Queries) DeleteTombstone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTombstone, id)
	return err
}

const deleteTombstonesByCalendar = `-- name: DeleteTombstonesByCalendar :exec
DELETE FROM tombstones WHERE calendar_id = ?
`

func (q *Queries) DeleteTombstonesByCalendar(ctx context.Context, calendarID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTombstonesByCalendar, calendarID)
	return err
}

const getSyncResource = `-- name: GetSyncResource :one
SELECT id, calendar_id, uid, owner_type, remote_url, etag, dirty, sync_strategy FROM sync_resources WHERE calendar_id = ? AND uid = ?
`

type GetSyncResourceParams struct {
	CalendarID int64
	Uid        string
}

func (q *Queries) GetSyncResource(ctx context.Context, arg GetSyncResourceParams) (SyncResource, error) {
	row := q.db.QueryRowContext(ctx, getSyncResource, arg.CalendarID, arg.Uid)
	var i SyncResource
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.OwnerType,
		&i.RemoteUrl,
		&i.Etag,
		&i.Dirty,
		&i.SyncStrategy,
	)
	return i, err
}

const listDirtySyncResources = `-- name: ListDirtySyncResources :many
SELECT id, calendar_id, uid, owner_type, remote_url, etag, dirty, sync_strategy FROM sync_resources WHERE calendar_id = ? AND dirty = 1 ORDER BY id
`

func (q *Queries) ListDirtySyncResources(ctx context.Context, calendarID int64) ([]SyncResource, error) {
	rows, err := q.db.QueryContext(ctx, listDirtySyncResources, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncResource
	for rows.Next() {
		var i SyncResource
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.OwnerType,
			&i.RemoteUrl,
			&i.Etag,
			&i.Dirty,
			&i.SyncStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncResourcesByCalendar = `-- name: ListSyncResourcesByCalendar :many
SELECT id, calendar_id, uid, owner_type, remote_url, etag, dirty, sync_strategy FROM sync_resources WHERE calendar_id = ? ORDER BY id
`

func (q *Queries) ListSyncResourcesByCalendar(ctx context.Context, calendarID int64) ([]SyncResource, error) {
	rows, err := q.db.QueryContext(ctx, listSyncResourcesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncResource
	for rows.Next() {
		var i SyncResource
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.OwnerType,
			&i.RemoteUrl,
			&i.Etag,
			&i.Dirty,
			&i.SyncStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstonesByCalendar = `-- name: ListTombstonesByCalendar :many
SELECT id, calendar_id, uid, remote_url, deleted_at FROM tombstones WHERE calendar_id = ? ORDER BY deleted_at
`

func (q *Queries) ListTombstonesByCalendar(ctx context.Context, calendarID int64) ([]Tombstone, error) {
	rows, err := q.db.QueryContext(ctx, listTombstonesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tombstone
	for rows.Next() {
		var i Tombstone
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.RemoteUrl,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncResourceDirty = `-- name: MarkSyncResourceDirty :exec
UPDATE sync_resources SET dirty = 1 WHERE calendar_id = ? AND uid = ?
`

type MarkSyncResourceDirtyParams struct {
	CalendarID int64
	Uid        string
}

func (q *Queries) MarkSyncResourceDirty(ctx context.Context, arg MarkSyncResourceDirtyParams) error {
	_, err := q.db.ExecContext(ctx, markSyncResourceDirty, arg.CalendarID, arg.Uid)
	return err
}

const upsertSyncResource = `-- name: UpsertSyncResource :exec
INSERT INTO sync_resources (calendar_id, uid, owner_type, remote_url, etag, dirty, sync_strategy)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(calendar_id, uid) DO UPDATE SET
    remote_url = excluded.remote_url,
    etag = excluded.etag,
    dirty = MAX(sync_resources.dirty, excluded.dirty),
    sync_strategy = excluded.sync_strategy
`

type UpsertSyncResourceParams struct {
	CalendarID   int64
	Uid          string
	OwnerType    string
	RemoteUrl    string
	Etag         string
	Dirty        int64
	SyncStrategy string
}

func (q *Queries) UpsertSyncResource(ctx context.Context, arg UpsertSyncResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncResource,
		arg.CalendarID,
		arg.Uid,
		arg.OwnerType,
		arg.RemoteUrl,
		arg.Etag,
		arg.Dirty,
		arg.SyncStrategy,
	)
	return err
}
