// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timezones.sql

package storage

import (
	"context"
)

const deleteTimezone = `-- name: DeleteTimezone :exec
DELETE FROM timezones WHERE tzid = ?
`

func (q *Queries) DeleteTimezone(ctx context.Context, tzid string) error {
	_, err := q.db.ExecContext(ctx, deleteTimezone, tzid)
	return err
}

const getTimezone = `-- name: GetTimezone :one
SELECT tzid, vtimezone_data, created_at, source FROM timezones WHERE tzid = ?
`

func (q *Queries) GetTimezone(ctx context.Context, tzid string) (Timezone, error) {
	row := q.db.QueryRowContext(ctx, getTimezone, tzid)
	var i Timezone
	err := row.Scan(
		&i.Tzid,
		&i.VtimezoneData,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const listTimezones = `-- name: ListTimezones :many
SELECT tzid, vtimezone_data, created_at, source FROM timezones ORDER BY tzid
`

func (q *Queries) ListTimezones(ctx context.Context) ([]Timezone, error) {
	rows, err := q.db.QueryContext(ctx, listTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timezone
	for rows.Next() {
		var i Timezone
		if err := rows.Scan(
			&i.Tzid,
			&i.VtimezoneData,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTimezone = `-- name: UpsertTimezone :one
INSERT INTO timezones (tzid, vtimezone_data)
VALUES (?, ?)
ON CONFLICT(tzid) DO UPDATE SET
    vtimezone_data = excluded.vtimezone_data
RETURNING tzid, vtimezone_data, created_at, source
`

type UpsertTimezoneParams struct {
	Tzid          string
	VtimezoneData string
}

func (q *Queries) UpsertTimezone(ctx context.Context, arg UpsertTimezoneParams) (Timezone, error) {
	row := q.db.QueryRowContext(ctx, upsertTimezone, arg.Tzid, arg.VtimezoneData)
	var i Timezone
	err := row.Scan(
		&i.Tzid,
		&i.VtimezoneData,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}
