// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_alarm_state.sql

package storage

import (
	"context"
	"database/sql"
)

const countTodoAlarmStates = `-- name: CountTodoAlarmStates :one
SELECT COUNT(*) FROM todo_alarm_state WHERE todo_id = ?
`

func (q *Queries) CountTodoAlarmStates(ctx context.Context, todoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoAlarmStates, todoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTodoAlarmState = `-- name: DeleteTodoAlarmState :exec
DELETE FROM todo_alarm_state WHERE id = ?
`

func (q *Queries) DeleteTodoAlarmState(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAlarmState, id)
	return err
}

const getTodoAlarmState = `-- name: GetTodoAlarmState :one
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE alarm_id = ? AND trigger_at = ?
`

type GetTodoAlarmStateParams struct {
	AlarmID   int64
	TriggerAt string
}

func (q *Queries) GetTodoAlarmState(ctx context.Context, arg GetTodoAlarmStateParams) (TodoAlarmState, error) {
	row := q.db.QueryRowContext(ctx, getTodoAlarmState, arg.AlarmID, arg.TriggerAt)
	var i TodoAlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.TodoID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const insertTodoAlarmState = `-- name: InsertTodoAlarmState :one
INSERT INTO todo_alarm_state (alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to
`

type InsertTodoAlarmStateParams struct {
	AlarmID   int64
	TodoID    int64
	TriggerAt string
	FiredAt   sql.NullString
	AckedAt   sql.NullString
	SnoozedTo sql.NullString
}

func (q *Queries) InsertTodoAlarmState(ctx context.Context, arg InsertTodoAlarmStateParams) (TodoAlarmState, error) {
	row := q.db.QueryRowContext(ctx, insertTodoAlarmState,
		arg.AlarmID,
		arg.TodoID,
		arg.TriggerAt,
		arg.FiredAt,
		arg.AckedAt,
		arg.SnoozedTo,
	)
	var i TodoAlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.TodoID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const listExpiredTodoSnoozed = `-- name: ListExpiredTodoSnoozed :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE snoozed_to IS NOT NULL AND snoozed_to <= ?
ORDER BY snoozed_to
`

func (q *Queries) ListExpiredTodoSnoozed(ctx context.Context, snoozedTo sql.NullString) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredTodoSnoozed, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiredTodoAlarmStates = `-- name: ListFiredTodoAlarmStates :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE todo_id = ? AND fired_at IS NOT NULL AND acked_at IS NULL AND snoozed_to IS NULL
ORDER BY fired_at DESC
`

func (q *Queries) ListFiredTodoAlarmStates(ctx context.Context, todoID int64) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listFiredTodoAlarmStates, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoAlarmStates = `-- name: ListTodoAlarmStates :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE todo_id = ? 
ORDER BY trigger_at DESC
`

func (q *Queries) ListTodoAlarmStates(ctx context.Context, todoID int64) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmStates, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoAlarmState = `-- name: UpdateTodoAlarmState :exec
UPDATE todo_alarm_state 
SET fired_at = ?, acked_at = ?, snoozed_to = ?
WHERE id = ?
`

type UpdateTodoAlarmStateParams struct {
	FiredAt   sql.NullString
	AckedAt   sql.NullString
	SnoozedTo sql.NullString
	ID        int64
}

func (q *Queries) UpdateTodoAlarmState(ctx context.Context, arg UpdateTodoAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoAlarmState,
		arg.FiredAt,
		arg.AckedAt,
		arg.SnoozedTo,
		arg.ID,
	)
	return err
}
