// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_resources.sql

package storage

import (
	"context"
)

const createTodoResource = `-- name: CreateTodoResource :one
INSERT INTO todo_resources (todo_id, text) VALUES (?, ?) RETURNING id, todo_id, text
`

type CreateTodoResourceParams struct {
	TodoID int64
	Text   string
}

func (q *Queries) CreateTodoResource(ctx context.Context, arg CreateTodoResourceParams) (TodoResource, error) {
	row := q.db.QueryRowContext(ctx, createTodoResource, arg.TodoID, arg.Text)
	var i TodoResource
	err := row.Scan(&i.ID, &i.TodoID, &i.Text)
	return i, err
}

const deleteTodoResourcesByTodoID = `-- name: DeleteTodoResourcesByTodoID :exec
DELETE FROM todo_resources WHERE todo_id = ?
`

func (q *Queries) DeleteTodoResourcesByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoResourcesByTodoID, todoID)
	return err
}

const listTodoResourcesByTodoID = `-- name: ListTodoResourcesByTodoID :many
SELECT id, todo_id, text FROM todo_resources WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoResourcesByTodoID(ctx context.Context, todoID int64) ([]TodoResource, error) {
	rows, err := q.db.QueryContext(ctx, listTodoResourcesByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoResource
	for rows.Next() {
		var i TodoResource
		if err := rows.Scan(&i.ID, &i.TodoID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
