// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_alarms.sql

package storage

import (
	"context"
)

const createTodoAlarm = `-- name: CreateTodoAlarm :one
INSERT INTO todo_alarms (todo_id, action, trigger_value, description, summary, repeat, duration, related)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, todo_id, "action", trigger_value, description, repeat, duration, related, summary
`

type CreateTodoAlarmParams struct {
	TodoID       int64
	Action       string
	TriggerValue string
	Description  string
	Summary      string
	Repeat       int64
	Duration     string
	Related      string
}

func (q *Queries) CreateTodoAlarm(ctx context.Context, arg CreateTodoAlarmParams) (TodoAlarm, error) {
	row := q.db.QueryRowContext(ctx, createTodoAlarm,
		arg.TodoID,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Summary,
		arg.Repeat,
		arg.Duration,
		arg.Related,
	)
	var i TodoAlarm
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Action,
		&i.TriggerValue,
		&i.Description,
		&i.Repeat,
		&i.Duration,
		&i.Related,
		&i.Summary,
	)
	return i, err
}

const deleteTodoAlarmsByTodoID = `-- name: DeleteTodoAlarmsByTodoID :exec
DELETE FROM todo_alarms WHERE todo_id = ?
`

func (q *Queries) DeleteTodoAlarmsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAlarmsByTodoID, todoID)
	return err
}

const listTodoAlarmsByTodoID = `-- name: ListTodoAlarmsByTodoID :many
SELECT id, todo_id, "action", trigger_value, description, repeat, duration, related, summary FROM todo_alarms WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoAlarmsByTodoID(ctx context.Context, todoID int64) ([]TodoAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarm
	for rows.Next() {
		var i TodoAlarm
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
