// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_attendees.sql

package storage

import (
	"context"
)

const createTodoAttendee = `-- name: CreateTodoAttendee :one
INSERT INTO todo_attendees (todo_id, email, name, rsvp_status, role, organizer)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, todo_id, email, name, rsvp_status, role, organizer
`

type CreateTodoAttendeeParams struct {
	TodoID     int64
	Email      string
	Name       string
	RsvpStatus string
	Role       string
	Organizer  int64
}

func (q *Queries) CreateTodoAttendee(ctx context.Context, arg CreateTodoAttendeeParams) (TodoAttendee, error) {
	row := q.db.QueryRowContext(ctx, createTodoAttendee,
		arg.TodoID,
		arg.Email,
		arg.Name,
		arg.RsvpStatus,
		arg.Role,
		arg.Organizer,
	)
	var i TodoAttendee
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Email,
		&i.Name,
		&i.RsvpStatus,
		&i.Role,
		&i.Organizer,
	)
	return i, err
}

const deleteTodoAttendeesByTodoID = `-- name: DeleteTodoAttendeesByTodoID :exec
DELETE FROM todo_attendees WHERE todo_id = ?
`

func (q *Queries) DeleteTodoAttendeesByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAttendeesByTodoID, todoID)
	return err
}

const listTodoAttendeesByTodoID = `-- name: ListTodoAttendeesByTodoID :many
SELECT id, todo_id, email, name, rsvp_status, role, organizer FROM todo_attendees WHERE todo_id = ? ORDER BY organizer DESC, name
`

func (q *Queries) ListTodoAttendeesByTodoID(ctx context.Context, todoID int64) ([]TodoAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAttendeesByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAttendee
	for rows.Next() {
		var i TodoAttendee
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Email,
			&i.Name,
			&i.RsvpStatus,
			&i.Role,
			&i.Organizer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
