// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_alarm_state.sql

package storage

import (
	"context"
)

const acknowledgeTodoAlarmState = `-- name: AcknowledgeTodoAlarmState :exec
UPDATE todo_alarm_state SET acked_at = ? WHERE id = ?
`

type AcknowledgeTodoAlarmStateParams struct {
	AckedAt *string
	ID      int64
}

func (q *Queries) AcknowledgeTodoAlarmState(ctx context.Context, arg AcknowledgeTodoAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeTodoAlarmState, arg.AckedAt, arg.ID)
	return err
}

const countTodoAlarmStates = `-- name: CountTodoAlarmStates :one
SELECT COUNT(*) FROM todo_alarm_state WHERE todo_id = ?
`

func (q *Queries) CountTodoAlarmStates(ctx context.Context, todoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoAlarmStates, todoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTodoAlarmState = `-- name: DeleteTodoAlarmState :exec
DELETE FROM todo_alarm_state WHERE id = ?
`

func (q *Queries) DeleteTodoAlarmState(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAlarmState, id)
	return err
}

const getTodoAlarmState = `-- name: GetTodoAlarmState :one
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE alarm_id = ? AND trigger_at = ?
`

type GetTodoAlarmStateParams struct {
	AlarmID   int64
	TriggerAt string
}

func (q *Queries) GetTodoAlarmState(ctx context.Context, arg GetTodoAlarmStateParams) (TodoAlarmState, error) {
	row := q.db.QueryRowContext(ctx, getTodoAlarmState, arg.AlarmID, arg.TriggerAt)
	var i TodoAlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.TodoID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const getTodoAlarmStateByID = `-- name: GetTodoAlarmStateByID :one
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state WHERE id = ?
`

func (q *Queries) GetTodoAlarmStateByID(ctx context.Context, id int64) (TodoAlarmState, error) {
	row := q.db.QueryRowContext(ctx, getTodoAlarmStateByID, id)
	var i TodoAlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.TodoID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const insertTodoAlarmState = `-- name: InsertTodoAlarmState :one
INSERT INTO todo_alarm_state (alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to
`

type InsertTodoAlarmStateParams struct {
	AlarmID   int64
	TodoID    int64
	TriggerAt string
	FiredAt   *string
	AckedAt   *string
	SnoozedTo *string
}

func (q *Queries) InsertTodoAlarmState(ctx context.Context, arg InsertTodoAlarmStateParams) (TodoAlarmState, error) {
	row := q.db.QueryRowContext(ctx, insertTodoAlarmState,
		arg.AlarmID,
		arg.TodoID,
		arg.TriggerAt,
		arg.FiredAt,
		arg.AckedAt,
		arg.SnoozedTo,
	)
	var i TodoAlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.TodoID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
	)
	return i, err
}

const listExpiredTodoSnoozed = `-- name: ListExpiredTodoSnoozed :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE snoozed_to IS NOT NULL AND snoozed_to <= ?
ORDER BY snoozed_to
`

func (q *Queries) ListExpiredTodoSnoozed(ctx context.Context, snoozedTo *string) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredTodoSnoozed, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiredTodoAlarmStates = `-- name: ListFiredTodoAlarmStates :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE todo_id = ? AND fired_at IS NOT NULL AND acked_at IS NULL AND snoozed_to IS NULL
ORDER BY fired_at DESC
`

func (q *Queries) ListFiredTodoAlarmStates(ctx context.Context, todoID int64) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listFiredTodoAlarmStates, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTodoAlarmStates = `-- name: ListPendingTodoAlarmStates :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state
WHERE acked_at IS NULL AND (fired_at IS NOT NULL OR snoozed_to IS NOT NULL)
ORDER BY trigger_at
`

func (q *Queries) ListPendingTodoAlarmStates(ctx context.Context) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTodoAlarmStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoAlarmStates = `-- name: ListTodoAlarmStates :many
SELECT id, alarm_id, todo_id, trigger_at, fired_at, acked_at, snoozed_to FROM todo_alarm_state 
WHERE todo_id = ? 
ORDER BY trigger_at DESC
`

func (q *Queries) ListTodoAlarmStates(ctx context.Context, todoID int64) ([]TodoAlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmStates, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmState
	for rows.Next() {
		var i TodoAlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.TodoID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAcknowledgedTodoAlarmStates = `-- name: PurgeAcknowledgedTodoAlarmStates :execrows
DELETE FROM todo_alarm_state WHERE acked_at IS NOT NULL AND trigger_at < ?
`

func (q *Queries) PurgeAcknowledgedTodoAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAcknowledgedTodoAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeStaleUnacknowledgedTodoAlarmStates = `-- name: PurgeStaleUnacknowledgedTodoAlarmStates :execrows
DELETE FROM todo_alarm_state
WHERE acked_at IS NULL
  AND trigger_at < ?
  AND (snoozed_to IS NULL OR snoozed_to < trigger_at)
`

func (q *Queries) PurgeStaleUnacknowledgedTodoAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeStaleUnacknowledgedTodoAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refireTodoAlarmState = `-- name: RefireTodoAlarmState :execrows
UPDATE todo_alarm_state SET fired_at = ?, snoozed_to = NULL
WHERE id = ? AND snoozed_to IS NOT NULL
`

type RefireTodoAlarmStateParams struct {
	FiredAt *string
	ID      int64
}

func (q *Queries) RefireTodoAlarmState(ctx context.Context, arg RefireTodoAlarmStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refireTodoAlarmState, arg.FiredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const snoozeTodoAlarmState = `-- name: SnoozeTodoAlarmState :exec
UPDATE todo_alarm_state SET snoozed_to = ? WHERE id = ?
`

type SnoozeTodoAlarmStateParams struct {
	SnoozedTo *string
	ID        int64
}

func (q *Queries) SnoozeTodoAlarmState(ctx context.Context, arg SnoozeTodoAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, snoozeTodoAlarmState, arg.SnoozedTo, arg.ID)
	return err
}
