// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package storage

import (
	"context"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos SET
    status = 'COMPLETED',
    completed_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    percent_complete = 100,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp
`

func (q *Queries) CompleteTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, completeTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    uid, calendar_id, summary, description, location,
    due_date, start_date, duration, completed_at, percent_complete,
    status, priority, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp
`

type CreateTodoParams struct {
	Uid             string
	CalendarID      int64
	Summary         string
	Description     string
	Location        string
	DueDate         string
	StartDate       string
	Duration        string
	CompletedAt     string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             string
	RecurrenceRule  string
	Timezone        string
	Sequence        int64
	Exdates         string
	Rdates          string
	RecurrenceID    string
	Geo             string
	Dtstamp         string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Dtstamp,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const deleteTodosByUID = `-- name: DeleteTodosByUID :exec
DELETE FROM todos WHERE uid = ?
`

func (q *Queries) DeleteTodosByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteTodosByUID, uid)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE id = ?
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const getTodoByUID = `-- name: GetTodoByUID :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE uid = ? AND recurrence_id = ''
`

func (q *Queries) GetTodoByUID(ctx context.Context, uid string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByUID, uid)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const getTodoByUIDAndRecurrenceID = `-- name: GetTodoByUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE uid = ? AND recurrence_id = ?
`

type GetTodoByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetTodoByUIDAndRecurrenceID(ctx context.Context, arg GetTodoByUIDAndRecurrenceIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const listAllTodos = `-- name: ListAllTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos ORDER BY due_date, summary
`

func (q *Queries) ListAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTodos = `-- name: ListRecurringTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE recurrence_rule != '' AND recurrence_id = ''
`

func (q *Queries) ListRecurringTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTodosByCalendar = `-- name: ListRecurringTodosByCalendar :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE recurrence_rule != '' AND recurrence_id = '' AND calendar_id = ?
`

func (q *Queries) ListRecurringTodosByCalendar(ctx context.Context, calendarID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTodosByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTodosFiltered = `-- name: ListRecurringTodosFiltered :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos
WHERE recurrence_rule != '' AND recurrence_id = ''
AND (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR status = ?2)
AND (?3 = 0 OR (status != 'COMPLETED' AND status != 'CANCELLED'))
ORDER BY due_date, summary
`

type ListRecurringTodosFilteredParams struct {
	CalendarID    interface{}
	FilterStatus  interface{}
	HideCompleted interface{}
}

func (q *Queries) ListRecurringTodosFiltered(ctx context.Context, arg ListRecurringTodosFilteredParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTodosFiltered, arg.CalendarID, arg.FilterStatus, arg.HideCompleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoOverridesByUID = `-- name: ListTodoOverridesByUID :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE uid = ? AND recurrence_id != '' ORDER BY recurrence_id
`

func (q *Queries) ListTodoOverridesByUID(ctx context.Context, uid string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodoOverridesByUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE status != 'COMPLETED' AND status != 'CANCELLED' ORDER BY due_date, summary
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByCalendar = `-- name: ListTodosByCalendar :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE calendar_id = ? AND status != 'COMPLETED' AND status != 'CANCELLED' ORDER BY due_date, summary
`

func (q *Queries) ListTodosByCalendar(ctx context.Context, calendarID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByDueDateRange = `-- name: ListTodosByDueDateRange :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE due_date >= ? AND due_date < ? ORDER BY due_date, summary
`

type ListTodosByDueDateRangeParams struct {
	DueDate   string
	DueDate_2 string
}

func (q *Queries) ListTodosByDueDateRange(ctx context.Context, arg ListTodosByDueDateRangeParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByDueDateRange, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByStatus = `-- name: ListTodosByStatus :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos WHERE status = ? ORDER BY due_date, summary
`

func (q *Queries) ListTodosByStatus(ctx context.Context, status string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosFiltered = `-- name: ListTodosFiltered :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos
WHERE recurrence_rule = '' AND recurrence_id = ''
AND (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR status = ?2)
AND (?3 = 0 OR (status != 'COMPLETED' AND status != 'CANCELLED'))
AND (?4 = '' OR due_date >= ?4)
AND (?5 = '' OR due_date < ?5)
ORDER BY due_date, summary
`

type ListTodosFilteredParams struct {
	CalendarID    interface{}
	FilterStatus  interface{}
	HideCompleted interface{}
	FromDate      interface{}
	ToDate        interface{}
}

func (q *Queries) ListTodosFiltered(ctx context.Context, arg ListTodosFilteredParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosFiltered,
		arg.CalendarID,
		arg.FilterStatus,
		arg.HideCompleted,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosForExport = `-- name: ListTodosForExport :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp FROM todos
WHERE (?1 = 0 OR calendar_id = ?1)
AND (?2 = '' OR EXISTS (SELECT 1 FROM todo_categories tc WHERE tc.todo_id = todos.id AND tc.category = ?2))
AND (?3 = '' OR status = ?3)
AND (?4 = 0 OR (?4 = 1 AND completed_at != '') OR (?4 = 2 AND completed_at = ''))
ORDER BY due_date ASC, summary ASC
`

type ListTodosForExportParams struct {
	CalendarID      interface{}
	Category        interface{}
	FilterStatus    interface{}
	CompletedFilter interface{}
}

func (q *Queries) ListTodosForExport(ctx context.Context, arg ListTodosForExportParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosForExport,
		arg.CalendarID,
		arg.Category,
		arg.FilterStatus,
		arg.CompletedFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET
    summary = ?, description = ?, location = ?,
    due_date = ?, start_date = ?, duration = ?,
    completed_at = ?, percent_complete = ?,
    status = ?, calendar_id = ?, priority = ?,
    class = ?, url = ?,
    recurrence_rule = ?, timezone = ?,
    sequence = sequence + 1,
    exdates = ?, rdates = ?, geo = ?,
    dtstamp = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp
`

type UpdateTodoParams struct {
	Summary         string
	Description     string
	Location        string
	DueDate         string
	StartDate       string
	Duration        string
	CompletedAt     string
	PercentComplete int64
	Status          string
	CalendarID      int64
	Priority        int64
	Class           string
	Url             string
	RecurrenceRule  string
	Timezone        string
	Exdates         string
	Rdates          string
	Geo             string
	Dtstamp         string
	ID              int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.CalendarID,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Exdates,
		arg.Rdates,
		arg.Geo,
		arg.Dtstamp,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}

const upsertTodoByUID = `-- name: UpsertTodoByUID :one
INSERT INTO todos (
    uid, calendar_id, summary, description, location,
    due_date, start_date, duration, completed_at, percent_complete,
    status, priority, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    summary = excluded.summary, description = excluded.description,
    location = excluded.location, due_date = excluded.due_date,
    start_date = excluded.start_date, duration = excluded.duration,
    completed_at = excluded.completed_at, percent_complete = excluded.percent_complete,
    status = excluded.status, priority = excluded.priority,
    class = excluded.class, url = excluded.url,
    recurrence_rule = excluded.recurrence_rule,
    timezone = excluded.timezone,
    sequence = MAX(excluded.sequence, todos.sequence + 1),
    exdates = excluded.exdates, rdates = excluded.rdates,
    geo = excluded.geo,
    dtstamp = excluded.dtstamp,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp
`

type UpsertTodoByUIDParams struct {
	Uid             string
	CalendarID      int64
	Summary         string
	Description     string
	Location        string
	DueDate         string
	StartDate       string
	Duration        string
	CompletedAt     string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             string
	RecurrenceRule  string
	Timezone        string
	Sequence        int64
	Exdates         string
	Rdates          string
	RecurrenceID    string
	Geo             string
	Dtstamp         string
}

func (q *Queries) UpsertTodoByUID(ctx context.Context, arg UpsertTodoByUIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, upsertTodoByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Dtstamp,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
	)
	return i, err
}
