// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_exdate_deletes.sql

package storage

import (
	"context"
)

const deleteTodoExdateDelete = `-- name: DeleteTodoExdateDelete :exec
DELETE FROM todo_exdate_deletes WHERE id = ?
`

func (q *Queries) DeleteTodoExdateDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoExdateDelete, id)
	return err
}

const getTodoExdateDeleteByUIDRecurrence = `-- name: GetTodoExdateDeleteByUIDRecurrence :one
SELECT id, calendar_id, uid, recurrence_id, deleted_at FROM todo_exdate_deletes WHERE uid = ? AND recurrence_id = ?
`

type GetTodoExdateDeleteByUIDRecurrenceParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetTodoExdateDeleteByUIDRecurrence(ctx context.Context, arg GetTodoExdateDeleteByUIDRecurrenceParams) (TodoExdateDelete, error) {
	row := q.db.QueryRowContext(ctx, getTodoExdateDeleteByUIDRecurrence, arg.Uid, arg.RecurrenceID)
	var i TodoExdateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.RecurrenceID,
		&i.DeletedAt,
	)
	return i, err
}

const purgeOldTodoExdateDeletes = `-- name: PurgeOldTodoExdateDeletes :execrows
DELETE FROM todo_exdate_deletes WHERE deleted_at < ?
`

func (q *Queries) PurgeOldTodoExdateDeletes(ctx context.Context, deletedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldTodoExdateDeletes, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordTodoExdateDelete = `-- name: RecordTodoExdateDelete :exec
INSERT INTO todo_exdate_deletes (calendar_id, uid, recurrence_id)
VALUES (?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type RecordTodoExdateDeleteParams struct {
	CalendarID   int64
	Uid          string
	RecurrenceID string
}

// Idempotent: deleting the same instance twice leaves exactly one log row.
func (q *Queries) RecordTodoExdateDelete(ctx context.Context, arg RecordTodoExdateDeleteParams) error {
	_, err := q.db.ExecContext(ctx, recordTodoExdateDelete, arg.CalendarID, arg.Uid, arg.RecurrenceID)
	return err
}
