// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_comments.sql

package storage

import (
	"context"
)

const createTodoComment = `-- name: CreateTodoComment :one
INSERT INTO todo_comments (todo_id, text) VALUES (?, ?) RETURNING id, todo_id, text
`

type CreateTodoCommentParams struct {
	TodoID int64
	Text   string
}

func (q *Queries) CreateTodoComment(ctx context.Context, arg CreateTodoCommentParams) (TodoComment, error) {
	row := q.db.QueryRowContext(ctx, createTodoComment, arg.TodoID, arg.Text)
	var i TodoComment
	err := row.Scan(&i.ID, &i.TodoID, &i.Text)
	return i, err
}

const deleteTodoCommentsByTodoID = `-- name: DeleteTodoCommentsByTodoID :exec
DELETE FROM todo_comments WHERE todo_id = ?
`

func (q *Queries) DeleteTodoCommentsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoCommentsByTodoID, todoID)
	return err
}

const listTodoCommentsByTodoID = `-- name: ListTodoCommentsByTodoID :many
SELECT id, todo_id, text FROM todo_comments WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoCommentsByTodoID(ctx context.Context, todoID int64) ([]TodoComment, error) {
	rows, err := q.db.QueryContext(ctx, listTodoCommentsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoComment
	for rows.Next() {
		var i TodoComment
		if err := rows.Scan(&i.ID, &i.TodoID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
