// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_categories.sql

package storage

import (
	"context"
)

const createTodoCategory = `-- name: CreateTodoCategory :one
INSERT INTO todo_categories (todo_id, category) VALUES (?, ?) RETURNING todo_id, category
`

type CreateTodoCategoryParams struct {
	TodoID   int64
	Category string
}

func (q *Queries) CreateTodoCategory(ctx context.Context, arg CreateTodoCategoryParams) (TodoCategory, error) {
	row := q.db.QueryRowContext(ctx, createTodoCategory, arg.TodoID, arg.Category)
	var i TodoCategory
	err := row.Scan(&i.TodoID, &i.Category)
	return i, err
}

const deleteCategoriesByTodoID = `-- name: DeleteCategoriesByTodoID :exec
DELETE FROM todo_categories WHERE todo_id = ?
`

func (q *Queries) DeleteCategoriesByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategoriesByTodoID, todoID)
	return err
}

const listAllTodoCategories = `-- name: ListAllTodoCategories :many
SELECT DISTINCT category FROM todo_categories ORDER BY category
`

func (q *Queries) ListAllTodoCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllTodoCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByTodoID = `-- name: ListCategoriesByTodoID :many
SELECT todo_id, category FROM todo_categories WHERE todo_id = ? ORDER BY category
`

func (q *Queries) ListCategoriesByTodoID(ctx context.Context, todoID int64) ([]TodoCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoCategory
	for rows.Next() {
		var i TodoCategory
		if err := rows.Scan(&i.TodoID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
