// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_alarms.sql

package storage

import (
	"context"
)

const createTodoAlarm = `-- name: CreateTodoAlarm :one
INSERT INTO todo_alarms (todo_id, uid, action, trigger_value, description, summary, repeat, duration, related, acknowledged, attach_uri, attach_fmttype)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, todo_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype
`

type CreateTodoAlarmParams struct {
	TodoID        int64
	Uid           string
	Action        string
	TriggerValue  string
	Description   string
	Summary       string
	Repeat        int64
	Duration      string
	Related       string
	Acknowledged  string
	AttachUri     string
	AttachFmttype string
}

func (q *Queries) CreateTodoAlarm(ctx context.Context, arg CreateTodoAlarmParams) (TodoAlarm, error) {
	row := q.db.QueryRowContext(ctx, createTodoAlarm,
		arg.TodoID,
		arg.Uid,
		arg.Action,
		arg.TriggerValue,
		arg.Description,
		arg.Summary,
		arg.Repeat,
		arg.Duration,
		arg.Related,
		arg.Acknowledged,
		arg.AttachUri,
		arg.AttachFmttype,
	)
	var i TodoAlarm
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Action,
		&i.TriggerValue,
		&i.Description,
		&i.Repeat,
		&i.Duration,
		&i.Related,
		&i.Summary,
		&i.Uid,
		&i.Acknowledged,
		&i.AttachUri,
		&i.AttachFmttype,
	)
	return i, err
}

const deleteTodoAlarmsByTodoID = `-- name: DeleteTodoAlarmsByTodoID :exec
DELETE FROM todo_alarms WHERE todo_id = ?
`

func (q *Queries) DeleteTodoAlarmsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAlarmsByTodoID, todoID)
	return err
}

const listTodoAlarmsByTodoID = `-- name: ListTodoAlarmsByTodoID :many
SELECT id, todo_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype FROM todo_alarms WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoAlarmsByTodoID(ctx context.Context, todoID int64) ([]TodoAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarm
	for rows.Next() {
		var i TodoAlarm
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
			&i.Acknowledged,
			&i.AttachUri,
			&i.AttachFmttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoAlarmsWithEmptyUID = `-- name: ListTodoAlarmsWithEmptyUID :many
SELECT id, todo_id, "action", trigger_value, description, repeat, duration, related, summary, uid, acknowledged, attach_uri, attach_fmttype FROM todo_alarms WHERE uid = ''
`

func (q *Queries) ListTodoAlarmsWithEmptyUID(ctx context.Context) ([]TodoAlarm, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmsWithEmptyUID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarm
	for rows.Next() {
		var i TodoAlarm
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Action,
			&i.TriggerValue,
			&i.Description,
			&i.Repeat,
			&i.Duration,
			&i.Related,
			&i.Summary,
			&i.Uid,
			&i.Acknowledged,
			&i.AttachUri,
			&i.AttachFmttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoAlarmUID = `-- name: UpdateTodoAlarmUID :exec
UPDATE todo_alarms SET uid = ? WHERE id = ?
`

type UpdateTodoAlarmUIDParams struct {
	Uid string
	ID  int64
}

func (q *Queries) UpdateTodoAlarmUID(ctx context.Context, arg UpdateTodoAlarmUIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoAlarmUID, arg.Uid, arg.ID)
	return err
}
