// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_attachments.sql

package storage

import (
	"context"
)

const createTodoAttachment = `-- name: CreateTodoAttachment :one
INSERT INTO todo_attachments (todo_id, uri, fmttype, data, filename) VALUES (?, ?, ?, ?, ?) RETURNING id, todo_id, uri, fmttype, data, filename
`

type CreateTodoAttachmentParams struct {
	TodoID   int64
	Uri      string
	Fmttype  string
	Data     []byte
	Filename string
}

func (q *Queries) CreateTodoAttachment(ctx context.Context, arg CreateTodoAttachmentParams) (TodoAttachment, error) {
	row := q.db.QueryRowContext(ctx, createTodoAttachment,
		arg.TodoID,
		arg.Uri,
		arg.Fmttype,
		arg.Data,
		arg.Filename,
	)
	var i TodoAttachment
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const deleteTodoAttachmentsByTodoID = `-- name: DeleteTodoAttachmentsByTodoID :exec
DELETE FROM todo_attachments WHERE todo_id = ?
`

func (q *Queries) DeleteTodoAttachmentsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAttachmentsByTodoID, todoID)
	return err
}

const getTodoAttachment = `-- name: GetTodoAttachment :one
SELECT id, todo_id, uri, fmttype, data, filename FROM todo_attachments WHERE id = ?
`

func (q *Queries) GetTodoAttachment(ctx context.Context, id int64) (TodoAttachment, error) {
	row := q.db.QueryRowContext(ctx, getTodoAttachment, id)
	var i TodoAttachment
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Uri,
		&i.Fmttype,
		&i.Data,
		&i.Filename,
	)
	return i, err
}

const listTodoAttachmentsByTodoID = `-- name: ListTodoAttachmentsByTodoID :many
SELECT id, todo_id, uri, fmttype, data, filename FROM todo_attachments WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoAttachmentsByTodoID(ctx context.Context, todoID int64) ([]TodoAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAttachmentsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAttachment
	for rows.Next() {
		var i TodoAttachment
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Uri,
			&i.Fmttype,
			&i.Data,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
