// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_alarm_attendees.sql

package storage

import (
	"context"
)

const createTodoAlarmAttendee = `-- name: CreateTodoAlarmAttendee :one
INSERT INTO todo_alarm_attendees (alarm_id, email, name) VALUES (?, ?, ?) RETURNING id, alarm_id, email, name
`

type CreateTodoAlarmAttendeeParams struct {
	AlarmID int64
	Email   string
	Name    *string
}

func (q *Queries) CreateTodoAlarmAttendee(ctx context.Context, arg CreateTodoAlarmAttendeeParams) (TodoAlarmAttendee, error) {
	row := q.db.QueryRowContext(ctx, createTodoAlarmAttendee, arg.AlarmID, arg.Email, arg.Name)
	var i TodoAlarmAttendee
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const deleteTodoAlarmAttendeesByAlarmID = `-- name: DeleteTodoAlarmAttendeesByAlarmID :exec
DELETE FROM todo_alarm_attendees WHERE alarm_id = ?
`

func (q *Queries) DeleteTodoAlarmAttendeesByAlarmID(ctx context.Context, alarmID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoAlarmAttendeesByAlarmID, alarmID)
	return err
}

const listTodoAlarmAttendeesByAlarmID = `-- name: ListTodoAlarmAttendeesByAlarmID :many
SELECT id, alarm_id, email, name FROM todo_alarm_attendees WHERE alarm_id = ? ORDER BY id
`

func (q *Queries) ListTodoAlarmAttendeesByAlarmID(ctx context.Context, alarmID int64) ([]TodoAlarmAttendee, error) {
	rows, err := q.db.QueryContext(ctx, listTodoAlarmAttendeesByAlarmID, alarmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoAlarmAttendee
	for rows.Next() {
		var i TodoAlarmAttendee
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
