// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_relations.sql

package storage

import (
	"context"
)

const createTodoRelation = `-- name: CreateTodoRelation :one
INSERT INTO todo_relations (todo_id, rel_type, rel_uid) VALUES (?, ?, ?) RETURNING id, todo_id, rel_type, rel_uid
`

type CreateTodoRelationParams struct {
	TodoID  int64
	RelType string
	RelUid  string
}

func (q *Queries) CreateTodoRelation(ctx context.Context, arg CreateTodoRelationParams) (TodoRelation, error) {
	row := q.db.QueryRowContext(ctx, createTodoRelation, arg.TodoID, arg.RelType, arg.RelUid)
	var i TodoRelation
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.RelType,
		&i.RelUid,
	)
	return i, err
}

const deleteTodoRelationsByTodoID = `-- name: DeleteTodoRelationsByTodoID :exec
DELETE FROM todo_relations WHERE todo_id = ?
`

func (q *Queries) DeleteTodoRelationsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoRelationsByTodoID, todoID)
	return err
}

const listTodoRelationsByTodoID = `-- name: ListTodoRelationsByTodoID :many
SELECT id, todo_id, rel_type, rel_uid FROM todo_relations WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoRelationsByTodoID(ctx context.Context, todoID int64) ([]TodoRelation, error) {
	rows, err := q.db.QueryContext(ctx, listTodoRelationsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoRelation
	for rows.Next() {
		var i TodoRelation
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.RelType,
			&i.RelUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
