// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_contacts.sql

package storage

import (
	"context"
)

const createTodoContact = `-- name: CreateTodoContact :one
INSERT INTO todo_contacts (todo_id, text) VALUES (?, ?) RETURNING id, todo_id, text
`

type CreateTodoContactParams struct {
	TodoID int64
	Text   string
}

func (q *Queries) CreateTodoContact(ctx context.Context, arg CreateTodoContactParams) (TodoContact, error) {
	row := q.db.QueryRowContext(ctx, createTodoContact, arg.TodoID, arg.Text)
	var i TodoContact
	err := row.Scan(&i.ID, &i.TodoID, &i.Text)
	return i, err
}

const deleteTodoContactsByTodoID = `-- name: DeleteTodoContactsByTodoID :exec
DELETE FROM todo_contacts WHERE todo_id = ?
`

func (q *Queries) DeleteTodoContactsByTodoID(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodoContactsByTodoID, todoID)
	return err
}

const listTodoContactsByTodoID = `-- name: ListTodoContactsByTodoID :many
SELECT id, todo_id, text FROM todo_contacts WHERE todo_id = ? ORDER BY id
`

func (q *Queries) ListTodoContactsByTodoID(ctx context.Context, todoID int64) ([]TodoContact, error) {
	rows, err := q.db.QueryContext(ctx, listTodoContactsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoContact
	for rows.Next() {
		var i TodoContact
		if err := rows.Scan(&i.ID, &i.TodoID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
