// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: x_properties.sql

package storage

import (
	"context"
)

const deleteXPropertiesByOwner = `-- name: DeleteXPropertiesByOwner :exec
DELETE FROM x_properties
WHERE owner_type = ? AND owner_id = ?
`

type DeleteXPropertiesByOwnerParams struct {
	OwnerType string
	OwnerID   int64
}

func (q *Queries) DeleteXPropertiesByOwner(ctx context.Context, arg DeleteXPropertiesByOwnerParams) error {
	_, err := q.db.ExecContext(ctx, deleteXPropertiesByOwner, arg.OwnerType, arg.OwnerID)
	return err
}

const insertXProperty = `-- name: InsertXProperty :exec
INSERT INTO x_properties (owner_type, owner_id, name, value, params)
VALUES (?, ?, ?, ?, ?)
`

type InsertXPropertyParams struct {
	OwnerType string
	OwnerID   int64
	Name      string
	Value     string
	Params    string
}

func (q *Queries) InsertXProperty(ctx context.Context, arg InsertXPropertyParams) error {
	_, err := q.db.ExecContext(ctx, insertXProperty,
		arg.OwnerType,
		arg.OwnerID,
		arg.Name,
		arg.Value,
		arg.Params,
	)
	return err
}

const listXPropertiesByOwner = `-- name: ListXPropertiesByOwner :many
SELECT id, owner_type, owner_id, name, value, params
FROM x_properties
WHERE owner_type = ? AND owner_id = ?
ORDER BY id
`

type ListXPropertiesByOwnerParams struct {
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ListXPropertiesByOwner(ctx context.Context, arg ListXPropertiesByOwnerParams) ([]XProperty, error) {
	rows, err := q.db.QueryContext(ctx, listXPropertiesByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XProperty
	for rows.Next() {
		var i XProperty
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Name,
			&i.Value,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
